/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AGwindowAffichage (void);
GtkWidget* create_AGwindowAjout (void);
GtkWidget* create_AGwindowModifier (void);
GtkWidget* create_AGwindowCatalogue (void);
GtkWidget* create_AGwindowConfirmation (void);
