/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed1;
  GtkWidget *entryuser;
  GtkWidget *entrypass;
  GtkWidget *labeluser;
  GtkWidget *label4;
  GtkWidget *password;
  GtkWidget *image1;
  GtkWidget *labelerreur;
  GtkWidget *button;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label3;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window2), fixed1);

  entryuser = gtk_entry_new ();
  gtk_widget_show (entryuser);
  gtk_fixed_put (GTK_FIXED (fixed1), entryuser, 328, 224);
  gtk_widget_set_size_request (entryuser, 230, 35);
  gtk_entry_set_visibility (GTK_ENTRY (entryuser), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryuser), 8226);

  entrypass = gtk_entry_new ();
  gtk_widget_show (entrypass);
  gtk_fixed_put (GTK_FIXED (fixed1), entrypass, 328, 304);
  gtk_widget_set_size_request (entrypass, 230, 35);
  gtk_entry_set_visibility (GTK_ENTRY (entrypass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypass), 8226);

  labeluser = gtk_label_new (_("login"));
  gtk_widget_show (labeluser);
  gtk_fixed_put (GTK_FIXED (fixed1), labeluser, 136, 216);
  gtk_widget_set_size_request (labeluser, 62, 49);

  label4 = gtk_label_new (_("nouveau sur sky travel ! s'inscrire"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 232, 504);
  gtk_widget_set_size_request (label4, 400, 40);

  password = gtk_label_new (_("password"));
  gtk_widget_show (password);
  gtk_fixed_put (GTK_FIXED (fixed1), password, 120, 304);
  gtk_widget_set_size_request (password, 119, 25);

  image1 = create_pixmap (window2, "zz.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 0);
  gtk_widget_set_size_request (image1, 805, 160);

  labelerreur = gtk_label_new ("");
  gtk_widget_show (labelerreur);
  gtk_fixed_put (GTK_FIXED (fixed1), labelerreur, 112, 368);
  gtk_widget_set_size_request (labelerreur, 600, 35);

  button = gtk_button_new ();
  gtk_widget_show (button);
  gtk_fixed_put (GTK_FIXED (fixed1), button, 360, 408);
  gtk_widget_set_size_request (button, 135, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("s'identifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button, "clicked",
                    G_CALLBACK (on_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window2, entryuser, "entryuser");
  GLADE_HOOKUP_OBJECT (window2, entrypass, "entrypass");
  GLADE_HOOKUP_OBJECT (window2, labeluser, "labeluser");
  GLADE_HOOKUP_OBJECT (window2, label4, "label4");
  GLADE_HOOKUP_OBJECT (window2, password, "password");
  GLADE_HOOKUP_OBJECT (window2, image1, "image1");
  GLADE_HOOKUP_OBJECT (window2, labelerreur, "labelerreur");
  GLADE_HOOKUP_OBJECT (window2, button, "button");
  GLADE_HOOKUP_OBJECT (window2, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window2, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window2, image2, "image2");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed2;
  GtkWidget *image7;
  GtkWidget *identifiant;
  GtkWidget *mot_de_passe;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *tel;
  GtkWidget *email;
  GtkWidget *adresse;
  GtkWidget *label23;
  GtkWidget *ajout;
  GtkWidget *ii;
  GtkWidget *mot;
  GtkWidget *n;
  GtkWidget *pr;
  GtkWidget *se;
  GtkWidget *label14;
  GtkWidget *te;
  GtkWidget *ema;
  GtkWidget *adres;
  GtkWidget *erreur1;
  GtkWidget *erreur2;
  GtkWidget *erreur3;
  GtkWidget *erreur4;
  GtkWidget *erreur5;
  GtkWidget *erreur6;
  GtkWidget *erreur7;
  GtkWidget *ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image9;
  GtkWidget *label7;
  GtkWidget *label22;
  GtkWidget *sexe;
  GtkWidget *modifier;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image10;
  GtkWidget *labele;
  GtkWidget *supprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image8;
  GtkWidget *label6;
  GtkWidget *deconnexion3;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *label21;
  GtkWidget *afficher;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image11;
  GtkWidget *labelee;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window3), fixed2);

  image7 = create_pixmap (window3, "p.png");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed2), image7, 0, 0);
  gtk_widget_set_size_request (image7, 805, 136);

  identifiant = gtk_entry_new ();
  gtk_widget_show (identifiant);
  gtk_fixed_put (GTK_FIXED (fixed2), identifiant, 360, 210);
  gtk_widget_set_size_request (identifiant, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiant), 8226);

  mot_de_passe = gtk_entry_new ();
  gtk_widget_show (mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed2), mot_de_passe, 360, 260);
  gtk_widget_set_size_request (mot_de_passe, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (mot_de_passe), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed2), nom, 360, 310);
  gtk_widget_set_size_request (nom, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom, 360, 360);
  gtk_widget_set_size_request (prenom, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed2), jour, 360, 510);
  gtk_widget_set_size_request (jour, 70, 34);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed2), mois, 465, 510);
  gtk_widget_set_size_request (mois, 70, 34);

  annee_adj = gtk_adjustment_new (1950, 1950, 2019, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed2), annee, 575, 510);
  gtk_widget_set_size_request (annee, 70, 34);

  tel = gtk_entry_new ();
  gtk_widget_show (tel);
  gtk_fixed_put (GTK_FIXED (fixed2), tel, 360, 560);
  gtk_widget_set_size_request (tel, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (tel), 8226);

  email = gtk_entry_new ();
  gtk_widget_show (email);
  gtk_fixed_put (GTK_FIXED (fixed2), email, 360, 610);
  gtk_widget_set_size_request (email, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (email), 8226);

  adresse = gtk_entry_new ();
  gtk_widget_show (adresse);
  gtk_fixed_put (GTK_FIXED (fixed2), adresse, 360, 660);
  gtk_widget_set_size_request (adresse, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (adresse), 8226);

  label23 = gtk_label_new (_("annee"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 575, 460);
  gtk_widget_set_size_request (label23, 50, 30);

  ajout = gtk_label_new (_("Ajouter client:"));
  gtk_widget_show (ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), ajout, 0, 144);
  gtk_widget_set_size_request (ajout, 200, 45);

  ii = gtk_label_new (_("identifiant"));
  gtk_widget_show (ii);
  gtk_fixed_put (GTK_FIXED (fixed2), ii, 145, 210);
  gtk_widget_set_size_request (ii, 100, 40);

  mot = gtk_label_new (_("mot de passe"));
  gtk_widget_show (mot);
  gtk_fixed_put (GTK_FIXED (fixed2), mot, 145, 260);
  gtk_widget_set_size_request (mot, 100, 40);

  n = gtk_label_new (_("nom"));
  gtk_widget_show (n);
  gtk_fixed_put (GTK_FIXED (fixed2), n, 145, 310);
  gtk_widget_set_size_request (n, 100, 40);

  pr = gtk_label_new (_("prenom"));
  gtk_widget_show (pr);
  gtk_fixed_put (GTK_FIXED (fixed2), pr, 145, 360);
  gtk_widget_set_size_request (pr, 100, 40);

  se = gtk_label_new (_("sexe"));
  gtk_widget_show (se);
  gtk_fixed_put (GTK_FIXED (fixed2), se, 145, 410);
  gtk_widget_set_size_request (se, 100, 40);

  label14 = gtk_label_new (_("date de naissance"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 145, 460);
  gtk_widget_set_size_request (label14, 125, 40);

  te = gtk_label_new (_("tel"));
  gtk_widget_show (te);
  gtk_fixed_put (GTK_FIXED (fixed2), te, 145, 560);
  gtk_widget_set_size_request (te, 100, 40);

  ema = gtk_label_new (_("email"));
  gtk_widget_show (ema);
  gtk_fixed_put (GTK_FIXED (fixed2), ema, 145, 610);
  gtk_widget_set_size_request (ema, 100, 40);

  adres = gtk_label_new (_("adresse"));
  gtk_widget_show (adres);
  gtk_fixed_put (GTK_FIXED (fixed2), adres, 145, 660);
  gtk_widget_set_size_request (adres, 100, 40);

  erreur1 = gtk_label_new ("");
  gtk_widget_show (erreur1);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur1, 608, 210);
  gtk_widget_set_size_request (erreur1, 200, 35);

  erreur2 = gtk_label_new ("");
  gtk_widget_show (erreur2);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur2, 584, 256);
  gtk_widget_set_size_request (erreur2, 200, 35);

  erreur3 = gtk_label_new ("");
  gtk_widget_show (erreur3);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur3, 592, 312);
  gtk_widget_set_size_request (erreur3, 200, 35);

  erreur4 = gtk_label_new ("");
  gtk_widget_show (erreur4);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur4, 600, 360);
  gtk_widget_set_size_request (erreur4, 200, 35);

  erreur5 = gtk_label_new ("");
  gtk_widget_show (erreur5);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur5, 584, 560);
  gtk_widget_set_size_request (erreur5, 200, 35);

  erreur6 = gtk_label_new ("");
  gtk_widget_show (erreur6);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur6, 584, 608);
  gtk_widget_set_size_request (erreur6, 200, 35);

  erreur7 = gtk_label_new ("");
  gtk_widget_show (erreur7);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur7, 584, 656);
  gtk_widget_set_size_request (erreur7, 200, 35);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter, 104, 792);
  gtk_widget_set_size_request (ajouter, 135, 45);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox4), image9, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("mois"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 465, 460);
  gtk_widget_set_size_request (label22, 50, 30);

  sexe = gtk_combo_box_entry_new_text ();
  gtk_widget_show (sexe);
  gtk_fixed_put (GTK_FIXED (fixed2), sexe, 360, 410);
  gtk_widget_set_size_request (sexe, 200, 54);
  gtk_combo_box_append_text (GTK_COMBO_BOX (sexe), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (sexe), _("femme"));

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), modifier, 488, 792);
  gtk_widget_set_size_request (modifier, 135, 45);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (modifier), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image10 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox5), image10, FALSE, FALSE, 0);

  labele = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (labele);
  gtk_box_pack_start (GTK_BOX (hbox5), labele, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), supprimer, 656, 792);
  gtk_widget_set_size_request (supprimer, 135, 45);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox3), image8, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  deconnexion3 = gtk_button_new ();
  gtk_widget_show (deconnexion3);
  gtk_fixed_put (GTK_FIXED (fixed2), deconnexion3, 656, 144);
  gtk_widget_set_size_request (deconnexion3, 135, 45);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (deconnexion3), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image5 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox2), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("deconnexion"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("jour"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 360, 460);
  gtk_widget_set_size_request (label21, 50, 30);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed2), afficher, 264, 792);
  gtk_widget_set_size_request (afficher, 169, 45);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (afficher), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image11 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox6), image11, FALSE, FALSE, 0);

  labelee = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (labelee);
  gtk_box_pack_start (GTK_BOX (hbox6), labelee, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) deconnexion3, "clicked",
                    G_CALLBACK (on_deconnexion3_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window3, image7, "image7");
  GLADE_HOOKUP_OBJECT (window3, identifiant, "identifiant");
  GLADE_HOOKUP_OBJECT (window3, mot_de_passe, "mot_de_passe");
  GLADE_HOOKUP_OBJECT (window3, nom, "nom");
  GLADE_HOOKUP_OBJECT (window3, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (window3, jour, "jour");
  GLADE_HOOKUP_OBJECT (window3, mois, "mois");
  GLADE_HOOKUP_OBJECT (window3, annee, "annee");
  GLADE_HOOKUP_OBJECT (window3, tel, "tel");
  GLADE_HOOKUP_OBJECT (window3, email, "email");
  GLADE_HOOKUP_OBJECT (window3, adresse, "adresse");
  GLADE_HOOKUP_OBJECT (window3, label23, "label23");
  GLADE_HOOKUP_OBJECT (window3, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (window3, ii, "ii");
  GLADE_HOOKUP_OBJECT (window3, mot, "mot");
  GLADE_HOOKUP_OBJECT (window3, n, "n");
  GLADE_HOOKUP_OBJECT (window3, pr, "pr");
  GLADE_HOOKUP_OBJECT (window3, se, "se");
  GLADE_HOOKUP_OBJECT (window3, label14, "label14");
  GLADE_HOOKUP_OBJECT (window3, te, "te");
  GLADE_HOOKUP_OBJECT (window3, ema, "ema");
  GLADE_HOOKUP_OBJECT (window3, adres, "adres");
  GLADE_HOOKUP_OBJECT (window3, erreur1, "erreur1");
  GLADE_HOOKUP_OBJECT (window3, erreur2, "erreur2");
  GLADE_HOOKUP_OBJECT (window3, erreur3, "erreur3");
  GLADE_HOOKUP_OBJECT (window3, erreur4, "erreur4");
  GLADE_HOOKUP_OBJECT (window3, erreur5, "erreur5");
  GLADE_HOOKUP_OBJECT (window3, erreur6, "erreur6");
  GLADE_HOOKUP_OBJECT (window3, erreur7, "erreur7");
  GLADE_HOOKUP_OBJECT (window3, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (window3, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window3, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window3, image9, "image9");
  GLADE_HOOKUP_OBJECT (window3, label7, "label7");
  GLADE_HOOKUP_OBJECT (window3, label22, "label22");
  GLADE_HOOKUP_OBJECT (window3, sexe, "sexe");
  GLADE_HOOKUP_OBJECT (window3, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (window3, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window3, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window3, image10, "image10");
  GLADE_HOOKUP_OBJECT (window3, labele, "labele");
  GLADE_HOOKUP_OBJECT (window3, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (window3, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window3, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window3, image8, "image8");
  GLADE_HOOKUP_OBJECT (window3, label6, "label6");
  GLADE_HOOKUP_OBJECT (window3, deconnexion3, "deconnexion3");
  GLADE_HOOKUP_OBJECT (window3, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window3, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window3, image5, "image5");
  GLADE_HOOKUP_OBJECT (window3, label5, "label5");
  GLADE_HOOKUP_OBJECT (window3, label21, "label21");
  GLADE_HOOKUP_OBJECT (window3, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (window3, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window3, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window3, image11, "image11");
  GLADE_HOOKUP_OBJECT (window3, labelee, "labelee");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed3;
  GtkWidget *image12;
  GtkWidget *treeview1;
  GtkWidget *label18;
  GtkWidget *retour;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image13;
  GtkWidget *label25;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window4), fixed3);

  image12 = create_pixmap (window4, "p.png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed3), image12, 0, 0);
  gtk_widget_set_size_request (image12, 800, 144);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 0, 248);
  gtk_widget_set_size_request (treeview1, 792, 248);

  label18 = gtk_label_new (_("liste des employ\303\251s:"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 296, 168);
  gtk_widget_set_size_request (label18, 200, 35);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed3), retour, 576, 600);
  gtk_widget_set_size_request (retour, 135, 45);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (retour), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox7), image13, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox7), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window4, image12, "image12");
  GLADE_HOOKUP_OBJECT (window4, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window4, label18, "label18");
  GLADE_HOOKUP_OBJECT (window4, retour, "retour");
  GLADE_HOOKUP_OBJECT (window4, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window4, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window4, image13, "image13");
  GLADE_HOOKUP_OBJECT (window4, label25, "label25");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed4;
  GtkWidget *id;
  GtkWidget *label50;
  GtkWidget *nid;
  GtkWidget *nmot_de_passe;
  GtkWidget *nnom;
  GtkWidget *nprenom;
  GtkObject *njour_adj;
  GtkWidget *njour;
  GtkObject *nmois_adj;
  GtkWidget *nmois;
  GtkObject *nannee_adj;
  GtkWidget *nannee;
  GtkWidget *ntel;
  GtkWidget *nemail;
  GtkWidget *nadresse;
  GtkWidget *label33;
  GtkWidget *nsexe;
  GtkWidget *label29;
  GtkWidget *label26;
  GtkWidget *label28;
  GtkWidget *label30;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label35;
  GtkWidget *label34;
  GtkWidget *label32;
  GtkWidget *label38;
  GtkWidget *label31;
  GtkWidget *image14;
  GtkWidget *label43;
  GtkWidget *modifierr;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image17;
  GtkWidget *label30eee;
  GtkWidget *buttonz4;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image23;
  GtkWidget *label53;
  GtkWidget *deconnexion5;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image18;
  GtkWidget *labele1;
  GtkWidget *valider;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image15;
  GtkWidget *label28ee;
  GtkWidget *label27;
  GtkWidget *afficher5;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image16;
  GtkWidget *label29e;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window5), fixed4);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed4), id, 424, 200);
  gtk_widget_set_size_request (id, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  label50 = gtk_label_new (_("identifiant rechercher:"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed4), label50, 208, 192);
  gtk_widget_set_size_request (label50, 176, 48);

  nid = gtk_entry_new ();
  gtk_widget_show (nid);
  gtk_fixed_put (GTK_FIXED (fixed4), nid, 390, 335);
  gtk_widget_set_size_request (nid, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nid), 8226);

  nmot_de_passe = gtk_entry_new ();
  gtk_widget_show (nmot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed4), nmot_de_passe, 390, 385);
  gtk_widget_set_size_request (nmot_de_passe, 207, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nmot_de_passe), 8226);

  nnom = gtk_entry_new ();
  gtk_widget_show (nnom);
  gtk_fixed_put (GTK_FIXED (fixed4), nnom, 392, 435);
  gtk_widget_set_size_request (nnom, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nnom), 8226);

  nprenom = gtk_entry_new ();
  gtk_widget_show (nprenom);
  gtk_fixed_put (GTK_FIXED (fixed4), nprenom, 392, 485);
  gtk_widget_set_size_request (nprenom, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nprenom), 8226);

  njour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  njour = gtk_spin_button_new (GTK_ADJUSTMENT (njour_adj), 1, 0);
  gtk_widget_show (njour);
  gtk_fixed_put (GTK_FIXED (fixed4), njour, 360, 635);
  gtk_widget_set_size_request (njour, 70, 34);

  nmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  nmois = gtk_spin_button_new (GTK_ADJUSTMENT (nmois_adj), 1, 0);
  gtk_widget_show (nmois);
  gtk_fixed_put (GTK_FIXED (fixed4), nmois, 448, 635);
  gtk_widget_set_size_request (nmois, 70, 34);

  nannee_adj = gtk_adjustment_new (1, 1950, 2019, 1, 10, 10);
  nannee = gtk_spin_button_new (GTK_ADJUSTMENT (nannee_adj), 1, 0);
  gtk_widget_show (nannee);
  gtk_fixed_put (GTK_FIXED (fixed4), nannee, 544, 635);
  gtk_widget_set_size_request (nannee, 70, 34);

  ntel = gtk_entry_new ();
  gtk_widget_show (ntel);
  gtk_fixed_put (GTK_FIXED (fixed4), ntel, 390, 685);
  gtk_widget_set_size_request (ntel, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (ntel), 8226);

  nemail = gtk_entry_new ();
  gtk_widget_show (nemail);
  gtk_fixed_put (GTK_FIXED (fixed4), nemail, 390, 735);
  gtk_widget_set_size_request (nemail, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nemail), 8226);

  nadresse = gtk_entry_new ();
  gtk_widget_show (nadresse);
  gtk_fixed_put (GTK_FIXED (fixed4), nadresse, 390, 785);
  gtk_widget_set_size_request (nadresse, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nadresse), 8226);

  label33 = gtk_label_new (_("prenom"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 185, 485);
  gtk_widget_set_size_request (label33, 135, 40);

  nsexe = gtk_combo_box_entry_new_text ();
  gtk_widget_show (nsexe);
  gtk_fixed_put (GTK_FIXED (fixed4), nsexe, 390, 535);
  gtk_widget_set_size_request (nsexe, 205, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (nsexe), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nsexe), _("femme"));

  label29 = gtk_label_new (_("Modifier clients"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 0, 152);
  gtk_widget_set_size_request (label29, 200, 35);

  label26 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 185, 335);
  gtk_widget_set_size_request (label26, 135, 40);

  label28 = gtk_label_new (_("nom"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed4), label28, 185, 435);
  gtk_widget_set_size_request (label28, 135, 40);

  label30 = gtk_label_new (_("adresse"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 184, 785);
  gtk_widget_set_size_request (label30, 135, 40);

  label46 = gtk_label_new ("");
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed4), label46, 600, 336);
  gtk_widget_set_size_request (label46, 200, 35);

  label47 = gtk_label_new ("");
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed4), label47, 608, 388);
  gtk_widget_set_size_request (label47, 200, 30);

  label41 = gtk_label_new ("");
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed4), label41, 616, 432);
  gtk_widget_set_size_request (label41, 200, 35);

  label42 = gtk_label_new ("");
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed4), label42, 608, 488);
  gtk_widget_set_size_request (label42, 200, 30);

  label44 = gtk_label_new ("");
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed4), label44, 600, 736);
  gtk_widget_set_size_request (label44, 200, 35);

  label45 = gtk_label_new ("");
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed4), label45, 600, 787);
  gtk_widget_set_size_request (label45, 200, 30);

  label36 = gtk_label_new (_("jour"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 376, 585);
  gtk_widget_set_size_request (label36, 53, 40);

  label37 = gtk_label_new (_("mois"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 464, 585);
  gtk_widget_set_size_request (label37, 53, 40);

  label35 = gtk_label_new (_("annee"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 560, 585);
  gtk_widget_set_size_request (label35, 53, 40);

  label34 = gtk_label_new (_("date de naissance"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 185, 585);
  gtk_widget_set_size_request (label34, 135, 40);

  label32 = gtk_label_new (_("tel"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 185, 685);
  gtk_widget_set_size_request (label32, 135, 40);

  label38 = gtk_label_new (_("sexe"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed4), label38, 185, 535);
  gtk_widget_set_size_request (label38, 135, 40);

  label31 = gtk_label_new (_("email"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 185, 735);
  gtk_widget_set_size_request (label31, 135, 40);

  image14 = create_pixmap (window5, "p.png");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed4), image14, 0, 0);
  gtk_widget_set_size_request (image14, 800, 144);

  label43 = gtk_label_new ("");
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed4), label43, 600, 688);
  gtk_widget_set_size_request (label43, 200, 30);

  modifierr = gtk_button_new ();
  gtk_widget_show (modifierr);
  gtk_fixed_put (GTK_FIXED (fixed4), modifierr, 456, 824);
  gtk_widget_set_size_request (modifierr, 135, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (modifierr), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image17 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox10), image17, FALSE, FALSE, 0);

  label30eee = gtk_label_new_with_mnemonic (_("modifierr"));
  gtk_widget_show (label30eee);
  gtk_box_pack_start (GTK_BOX (hbox10), label30eee, FALSE, FALSE, 0);

  buttonz4 = gtk_button_new ();
  gtk_widget_show (buttonz4);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonz4, 280, 824);
  gtk_widget_set_size_request (buttonz4, 135, 45);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonz4), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image23 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox14), image23, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox14), label53, FALSE, FALSE, 0);

  deconnexion5 = gtk_button_new ();
  gtk_widget_show (deconnexion5);
  gtk_fixed_put (GTK_FIXED (fixed4), deconnexion5, 664, 152);
  gtk_widget_set_size_request (deconnexion5, 135, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (deconnexion5), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image18 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox11), image18, FALSE, FALSE, 0);

  labele1 = gtk_label_new_with_mnemonic (_("deconnexion"));
  gtk_widget_show (labele1);
  gtk_box_pack_start (GTK_BOX (hbox11), labele1, FALSE, FALSE, 0);

  valider = gtk_button_new ();
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed4), valider, 320, 256);
  gtk_widget_set_size_request (valider, 135, 45);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (valider), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image15 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox8), image15, FALSE, FALSE, 0);

  label28ee = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label28ee);
  gtk_box_pack_start (GTK_BOX (hbox8), label28ee, FALSE, FALSE, 0);

  label27 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 185, 385);
  gtk_widget_set_size_request (label27, 135, 40);

  afficher5 = gtk_button_new ();
  gtk_widget_show (afficher5);
  gtk_fixed_put (GTK_FIXED (fixed4), afficher5, 624, 824);
  gtk_widget_set_size_request (afficher5, 135, 45);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (afficher5), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image16 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox9), image16, FALSE, FALSE, 0);

  label29e = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label29e);
  gtk_box_pack_start (GTK_BOX (hbox9), label29e, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modifierr, "clicked",
                    G_CALLBACK (on_modifierr_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonz4, "clicked",
                    G_CALLBACK (on_buttonz4_clicked),
                    NULL);
  g_signal_connect ((gpointer) deconnexion5, "clicked",
                    G_CALLBACK (on_deconnexion5_clicked),
                    NULL);
  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher5, "clicked",
                    G_CALLBACK (on_afficher5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window5, id, "id");
  GLADE_HOOKUP_OBJECT (window5, label50, "label50");
  GLADE_HOOKUP_OBJECT (window5, nid, "nid");
  GLADE_HOOKUP_OBJECT (window5, nmot_de_passe, "nmot_de_passe");
  GLADE_HOOKUP_OBJECT (window5, nnom, "nnom");
  GLADE_HOOKUP_OBJECT (window5, nprenom, "nprenom");
  GLADE_HOOKUP_OBJECT (window5, njour, "njour");
  GLADE_HOOKUP_OBJECT (window5, nmois, "nmois");
  GLADE_HOOKUP_OBJECT (window5, nannee, "nannee");
  GLADE_HOOKUP_OBJECT (window5, ntel, "ntel");
  GLADE_HOOKUP_OBJECT (window5, nemail, "nemail");
  GLADE_HOOKUP_OBJECT (window5, nadresse, "nadresse");
  GLADE_HOOKUP_OBJECT (window5, label33, "label33");
  GLADE_HOOKUP_OBJECT (window5, nsexe, "nsexe");
  GLADE_HOOKUP_OBJECT (window5, label29, "label29");
  GLADE_HOOKUP_OBJECT (window5, label26, "label26");
  GLADE_HOOKUP_OBJECT (window5, label28, "label28");
  GLADE_HOOKUP_OBJECT (window5, label30, "label30");
  GLADE_HOOKUP_OBJECT (window5, label46, "label46");
  GLADE_HOOKUP_OBJECT (window5, label47, "label47");
  GLADE_HOOKUP_OBJECT (window5, label41, "label41");
  GLADE_HOOKUP_OBJECT (window5, label42, "label42");
  GLADE_HOOKUP_OBJECT (window5, label44, "label44");
  GLADE_HOOKUP_OBJECT (window5, label45, "label45");
  GLADE_HOOKUP_OBJECT (window5, label36, "label36");
  GLADE_HOOKUP_OBJECT (window5, label37, "label37");
  GLADE_HOOKUP_OBJECT (window5, label35, "label35");
  GLADE_HOOKUP_OBJECT (window5, label34, "label34");
  GLADE_HOOKUP_OBJECT (window5, label32, "label32");
  GLADE_HOOKUP_OBJECT (window5, label38, "label38");
  GLADE_HOOKUP_OBJECT (window5, label31, "label31");
  GLADE_HOOKUP_OBJECT (window5, image14, "image14");
  GLADE_HOOKUP_OBJECT (window5, label43, "label43");
  GLADE_HOOKUP_OBJECT (window5, modifierr, "modifierr");
  GLADE_HOOKUP_OBJECT (window5, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window5, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window5, image17, "image17");
  GLADE_HOOKUP_OBJECT (window5, label30eee, "label30eee");
  GLADE_HOOKUP_OBJECT (window5, buttonz4, "buttonz4");
  GLADE_HOOKUP_OBJECT (window5, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window5, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window5, image23, "image23");
  GLADE_HOOKUP_OBJECT (window5, label53, "label53");
  GLADE_HOOKUP_OBJECT (window5, deconnexion5, "deconnexion5");
  GLADE_HOOKUP_OBJECT (window5, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window5, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window5, image18, "image18");
  GLADE_HOOKUP_OBJECT (window5, labele1, "labele1");
  GLADE_HOOKUP_OBJECT (window5, valider, "valider");
  GLADE_HOOKUP_OBJECT (window5, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window5, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window5, image15, "image15");
  GLADE_HOOKUP_OBJECT (window5, label28ee, "label28ee");
  GLADE_HOOKUP_OBJECT (window5, label27, "label27");
  GLADE_HOOKUP_OBJECT (window5, afficher5, "afficher5");
  GLADE_HOOKUP_OBJECT (window5, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window5, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window5, image16, "image16");
  GLADE_HOOKUP_OBJECT (window5, label29e, "label29e");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed5;
  GtkWidget *image19;
  GtkWidget *supp;
  GtkWidget *labelx;
  GtkWidget *label52;
  GtkWidget *confirmer;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image20;
  GtkWidget *label51;
  GtkWidget *debutemp;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image24;
  GtkWidget *label54;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window6), fixed5);

  image19 = create_pixmap (window6, "p.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed5), image19, 0, 0);
  gtk_widget_set_size_request (image19, 800, 136);

  supp = gtk_entry_new ();
  gtk_widget_show (supp);
  gtk_fixed_put (GTK_FIXED (fixed5), supp, 392, 240);
  gtk_widget_set_size_request (supp, 205, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (supp), 8226);

  labelx = gtk_label_new (_("\303\212tes-vous s\303\273r  de vouloir supprimer ce compte ?"));
  gtk_widget_show (labelx);
  gtk_fixed_put (GTK_FIXED (fixed5), labelx, 232, 152);
  gtk_widget_set_size_request (labelx, 400, 40);

  label52 = gtk_label_new (_("id supprimer"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed5), label52, 160, 240);
  gtk_widget_set_size_request (label52, 205, 35);

  confirmer = gtk_button_new ();
  gtk_widget_show (confirmer);
  gtk_fixed_put (GTK_FIXED (fixed5), confirmer, 432, 392);
  gtk_widget_set_size_request (confirmer, 135, 45);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (confirmer), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox12), image20, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("appliquer"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox12), label51, FALSE, FALSE, 0);

  debutemp = gtk_button_new ();
  gtk_widget_show (debutemp);
  gtk_fixed_put (GTK_FIXED (fixed5), debutemp, 208, 392);
  gtk_widget_set_size_request (debutemp, 135, 45);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (debutemp), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image24 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox15), image24, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("menu employer"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox15), label54, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) confirmer, "clicked",
                    G_CALLBACK (on_confirmer_clicked),
                    NULL);
  g_signal_connect ((gpointer) debutemp, "clicked",
                    G_CALLBACK (on_debutemp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window6, image19, "image19");
  GLADE_HOOKUP_OBJECT (window6, supp, "supp");
  GLADE_HOOKUP_OBJECT (window6, labelx, "labelx");
  GLADE_HOOKUP_OBJECT (window6, label52, "label52");
  GLADE_HOOKUP_OBJECT (window6, confirmer, "confirmer");
  GLADE_HOOKUP_OBJECT (window6, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window6, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window6, image20, "image20");
  GLADE_HOOKUP_OBJECT (window6, label51, "label51");
  GLADE_HOOKUP_OBJECT (window6, debutemp, "debutemp");
  GLADE_HOOKUP_OBJECT (window6, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window6, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window6, image24, "image24");
  GLADE_HOOKUP_OBJECT (window6, label54, "label54");

  return window6;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed6;
  GtkWidget *image22;
  GtkWidget *button3;
  GtkWidget *inscription;
  GtkWidget *connexion;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window1), fixed6);

  image22 = create_pixmap (window1, "ac.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed6), image22, 48, 0);
  gtk_widget_set_size_request (image22, 824, 464);

  button3 = gtk_button_new_with_mnemonic (_("catalogue"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed6), button3, 704, 144);
  gtk_widget_set_size_request (button3, 135, 45);

  inscription = gtk_button_new_with_mnemonic (_("inscription"));
  gtk_widget_show (inscription);
  gtk_fixed_put (GTK_FIXED (fixed6), inscription, 704, 208);
  gtk_widget_set_size_request (inscription, 135, 45);

  connexion = gtk_button_new_with_mnemonic (_("connexion"));
  gtk_widget_show (connexion);
  gtk_fixed_put (GTK_FIXED (fixed6), connexion, 704, 80);
  gtk_widget_set_size_request (connexion, 135, 45);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) inscription, "clicked",
                    G_CALLBACK (on_inscription_clicked),
                    NULL);
  g_signal_connect ((gpointer) connexion, "clicked",
                    G_CALLBACK (on_connexion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, image22, "image22");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, inscription, "inscription");
  GLADE_HOOKUP_OBJECT (window1, connexion, "connexion");

  return window1;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed7;
  GtkWidget *image26;
  GtkWidget *labelx55;
  GtkWidget *labelx56;
  GtkWidget *labelx57;
  GtkWidget *deconnexion7;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image27;
  GtkWidget *label5j8;
  GtkWidget *image25;
  GtkWidget *moncompte;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image28;
  GtkWidget *label59r;
  GtkWidget *resevation;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image30;
  GtkWidget *label61f;
  GtkWidget *reclamation;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image31;
  GtkWidget *label62;
  GtkWidget *nosclient;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image29;
  GtkWidget *label6h0;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("window7"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window7), fixed7);

  image26 = create_pixmap (window7, "addd.png");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed7), image26, 16, 144);
  gtk_widget_set_size_request (image26, 272, 312);

  labelx55 = gtk_label_new (_("Nom:    Fridhi"));
  gtk_widget_show (labelx55);
  gtk_fixed_put (GTK_FIXED (fixed7), labelx55, 64, 472);
  gtk_widget_set_size_request (labelx55, 135, 30);

  labelx56 = gtk_label_new (_("Prenom: Zahra"));
  gtk_widget_show (labelx56);
  gtk_fixed_put (GTK_FIXED (fixed7), labelx56, 72, 512);
  gtk_widget_set_size_request (labelx56, 130, 30);

  labelx57 = gtk_label_new (_("Titre: Responsable gestion"));
  gtk_widget_show (labelx57);
  gtk_fixed_put (GTK_FIXED (fixed7), labelx57, 80, 560);
  gtk_widget_set_size_request (labelx57, 197, 30);

  deconnexion7 = gtk_button_new ();
  gtk_widget_show (deconnexion7);
  gtk_fixed_put (GTK_FIXED (fixed7), deconnexion7, 585, 176);
  gtk_widget_set_size_request (deconnexion7, 135, 45);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (deconnexion7), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image27 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox16), image27, FALSE, FALSE, 0);

  label5j8 = gtk_label_new_with_mnemonic (_("deconnexion"));
  gtk_widget_show (label5j8);
  gtk_box_pack_start (GTK_BOX (hbox16), label5j8, FALSE, FALSE, 0);

  image25 = create_pixmap (window7, "p.png");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed7), image25, 0, 0);
  gtk_widget_set_size_request (image25, 808, 144);

  moncompte = gtk_button_new ();
  gtk_widget_show (moncompte);
  gtk_fixed_put (GTK_FIXED (fixed7), moncompte, 585, 264);
  gtk_widget_set_size_request (moncompte, 135, 45);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (moncompte), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image28 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox17), image28, FALSE, FALSE, 0);

  label59r = gtk_label_new_with_mnemonic (_("Mon compte"));
  gtk_widget_show (label59r);
  gtk_box_pack_start (GTK_BOX (hbox17), label59r, FALSE, FALSE, 0);

  resevation = gtk_button_new ();
  gtk_widget_show (resevation);
  gtk_fixed_put (GTK_FIXED (fixed7), resevation, 585, 448);
  gtk_widget_set_size_request (resevation, 135, 45);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (resevation), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image30 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox19), image30, FALSE, FALSE, 0);

  label61f = gtk_label_new_with_mnemonic (_("reservation"));
  gtk_widget_show (label61f);
  gtk_box_pack_start (GTK_BOX (hbox19), label61f, FALSE, FALSE, 0);

  reclamation = gtk_button_new ();
  gtk_widget_show (reclamation);
  gtk_fixed_put (GTK_FIXED (fixed7), reclamation, 585, 536);
  gtk_widget_set_size_request (reclamation, 135, 45);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (reclamation), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image31 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox20), image31, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("reclamation"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox20), label62, FALSE, FALSE, 0);

  nosclient = gtk_button_new ();
  gtk_widget_show (nosclient);
  gtk_fixed_put (GTK_FIXED (fixed7), nosclient, 585, 352);
  gtk_widget_set_size_request (nosclient, 135, 45);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (nosclient), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image29 = gtk_image_new_from_stock ("gtk-orientation-portrait", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox18), image29, FALSE, FALSE, 0);

  label6h0 = gtk_label_new_with_mnemonic (_("Nos clients"));
  gtk_widget_show (label6h0);
  gtk_box_pack_start (GTK_BOX (hbox18), label6h0, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) deconnexion7, "clicked",
                    G_CALLBACK (on_deconnexion7_clicked),
                    NULL);
  g_signal_connect ((gpointer) moncompte, "clicked",
                    G_CALLBACK (on_moncompte_clicked),
                    NULL);
  g_signal_connect ((gpointer) resevation, "clicked",
                    G_CALLBACK (on_resevation_clicked),
                    NULL);
  g_signal_connect ((gpointer) reclamation, "clicked",
                    G_CALLBACK (on_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) nosclient, "clicked",
                    G_CALLBACK (on_nosclient_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window7, image26, "image26");
  GLADE_HOOKUP_OBJECT (window7, labelx55, "labelx55");
  GLADE_HOOKUP_OBJECT (window7, labelx56, "labelx56");
  GLADE_HOOKUP_OBJECT (window7, labelx57, "labelx57");
  GLADE_HOOKUP_OBJECT (window7, deconnexion7, "deconnexion7");
  GLADE_HOOKUP_OBJECT (window7, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window7, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window7, image27, "image27");
  GLADE_HOOKUP_OBJECT (window7, label5j8, "label5j8");
  GLADE_HOOKUP_OBJECT (window7, image25, "image25");
  GLADE_HOOKUP_OBJECT (window7, moncompte, "moncompte");
  GLADE_HOOKUP_OBJECT (window7, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window7, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window7, image28, "image28");
  GLADE_HOOKUP_OBJECT (window7, label59r, "label59r");
  GLADE_HOOKUP_OBJECT (window7, resevation, "resevation");
  GLADE_HOOKUP_OBJECT (window7, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window7, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window7, image30, "image30");
  GLADE_HOOKUP_OBJECT (window7, label61f, "label61f");
  GLADE_HOOKUP_OBJECT (window7, reclamation, "reclamation");
  GLADE_HOOKUP_OBJECT (window7, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window7, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window7, image31, "image31");
  GLADE_HOOKUP_OBJECT (window7, label62, "label62");
  GLADE_HOOKUP_OBJECT (window7, nosclient, "nosclient");
  GLADE_HOOKUP_OBJECT (window7, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window7, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window7, image29, "image29");
  GLADE_HOOKUP_OBJECT (window7, label6h0, "label6h0");

  return window7;
}

GtkWidget*
create_window8 (void)
{
  GtkWidget *window8;
  GtkWidget *fixed8;
  GtkWidget *entry18z;
  GtkWidget *entry28z;
  GtkWidget *entry38z;
  GtkWidget *entry48z;
  GtkWidget *entry58z;
  GtkObject *spinbutton2jours_adj;
  GtkWidget *spinbutton2jours;
  GtkObject *spinbutton3mois_adj;
  GtkWidget *spinbutton3mois;
  GtkObject *spinbutton4annee_adj;
  GtkWidget *spinbutton4annee;
  GtkWidget *image33;
  GtkWidget *entry6z88;
  GtkWidget *image35;
  GtkWidget *label758z;
  GtkWidget *label698z;
  GtkWidget *label688z;
  GtkWidget *label7478z;
  GtkWidget *label738z;
  GtkWidget *label728z;
  GtkWidget *label718z;
  GtkWidget *comboboxentry18z;
  GtkWidget *label708z;
  GtkWidget *label678z;
  GtkWidget *label65zz;
  GtkWidget *entry1emptt;
  GtkWidget *label6715z;
  GtkWidget *deconnexion8;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image32;
  GtkWidget *label63;
  GtkWidget *label6687;
  GtkWidget *entry2empty;
  GtkWidget *label6717;
  GtkWidget *button4emp;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image36;
  GtkWidget *label6688;
  GtkWidget *validercemp;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image47;
  GtkWidget *label6716;

  window8 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8), _("window8"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window8), fixed8);

  entry18z = gtk_entry_new ();
  gtk_widget_show (entry18z);
  gtk_fixed_put (GTK_FIXED (fixed8), entry18z, 440, 312);
  gtk_widget_set_size_request (entry18z, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18z), 8226);

  entry28z = gtk_entry_new ();
  gtk_widget_show (entry28z);
  gtk_fixed_put (GTK_FIXED (fixed8), entry28z, 440, 216);
  gtk_widget_set_size_request (entry28z, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28z), 8226);

  entry38z = gtk_entry_new ();
  gtk_widget_show (entry38z);
  gtk_fixed_put (GTK_FIXED (fixed8), entry38z, 440, 360);
  gtk_widget_set_size_request (entry38z, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry38z), 8226);

  entry48z = gtk_entry_new ();
  gtk_widget_show (entry48z);
  gtk_fixed_put (GTK_FIXED (fixed8), entry48z, 448, 568);
  gtk_widget_set_size_request (entry48z, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry48z), 8226);

  entry58z = gtk_entry_new ();
  gtk_widget_show (entry58z);
  gtk_fixed_put (GTK_FIXED (fixed8), entry58z, 448, 624);
  gtk_widget_set_size_request (entry58z, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry58z), 8226);

  spinbutton2jours_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton2jours = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2jours_adj), 1, 0);
  gtk_widget_show (spinbutton2jours);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton2jours, 440, 504);
  gtk_widget_set_size_request (spinbutton2jours, 70, 34);

  spinbutton3mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton3mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3mois_adj), 1, 0);
  gtk_widget_show (spinbutton3mois);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton3mois, 528, 504);
  gtk_widget_set_size_request (spinbutton3mois, 70, 34);

  spinbutton4annee_adj = gtk_adjustment_new (1, 1950, 2019, 1, 10, 10);
  spinbutton4annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4annee_adj), 1, 0);
  gtk_widget_show (spinbutton4annee);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton4annee, 616, 504);
  gtk_widget_set_size_request (spinbutton4annee, 70, 34);

  image33 = create_pixmap (window8, "p.png");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed8), image33, 0, 0);
  gtk_widget_set_size_request (image33, 805, 141);

  entry6z88 = gtk_entry_new ();
  gtk_widget_show (entry6z88);
  gtk_fixed_put (GTK_FIXED (fixed8), entry6z88, 448, 672);
  gtk_widget_set_size_request (entry6z88, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6z88), 8226);

  image35 = create_pixmap (window8, "addd.png");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed8), image35, 0, 152);
  gtk_widget_set_size_request (image35, 280, 328);

  label758z = gtk_label_new (_("adresse"));
  gtk_widget_show (label758z);
  gtk_fixed_put (GTK_FIXED (fixed8), label758z, 344, 680);
  gtk_widget_set_size_request (label758z, 78, 21);

  label698z = gtk_label_new (_("email:"));
  gtk_widget_show (label698z);
  gtk_fixed_put (GTK_FIXED (fixed8), label698z, 352, 640);
  gtk_widget_set_size_request (label698z, 49, 17);

  label688z = gtk_label_new (_("tel:"));
  gtk_widget_show (label688z);
  gtk_fixed_put (GTK_FIXED (fixed8), label688z, 344, 584);
  gtk_widget_set_size_request (label688z, 52, 25);

  label7478z = gtk_label_new (_("annee"));
  gtk_widget_show (label7478z);
  gtk_fixed_put (GTK_FIXED (fixed8), label7478z, 624, 472);
  gtk_widget_set_size_request (label7478z, 49, 17);

  label738z = gtk_label_new (_("mois"));
  gtk_widget_show (label738z);
  gtk_fixed_put (GTK_FIXED (fixed8), label738z, 536, 472);
  gtk_widget_set_size_request (label738z, 49, 17);

  label728z = gtk_label_new (_("jour"));
  gtk_widget_show (label728z);
  gtk_fixed_put (GTK_FIXED (fixed8), label728z, 440, 472);
  gtk_widget_set_size_request (label728z, 64, 24);

  label718z = gtk_label_new (_("date de naissance"));
  gtk_widget_show (label718z);
  gtk_fixed_put (GTK_FIXED (fixed8), label718z, 312, 464);
  gtk_widget_set_size_request (label718z, 128, 32);

  comboboxentry18z = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry18z);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry18z, 440, 408);
  gtk_widget_set_size_request (comboboxentry18z, 206, 34);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry18z), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry18z), _("femme"));

  label708z = gtk_label_new (_("sexe:"));
  gtk_widget_show (label708z);
  gtk_fixed_put (GTK_FIXED (fixed8), label708z, 344, 416);
  gtk_widget_set_size_request (label708z, 52, 25);

  label678z = gtk_label_new (_("prenom:"));
  gtk_widget_show (label678z);
  gtk_fixed_put (GTK_FIXED (fixed8), label678z, 344, 368);
  gtk_widget_set_size_request (label678z, 60, 23);

  label65zz = gtk_label_new (_("nom:"));
  gtk_widget_show (label65zz);
  gtk_fixed_put (GTK_FIXED (fixed8), label65zz, 328, 320);
  gtk_widget_set_size_request (label65zz, 66, 37);

  entry1emptt = gtk_entry_new ();
  gtk_widget_show (entry1emptt);
  gtk_fixed_put (GTK_FIXED (fixed8), entry1emptt, 80, 528);
  gtk_widget_set_size_request (entry1emptt, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1emptt), 8226);

  label6715z = gtk_label_new (_("identifiant "));
  gtk_widget_show (label6715z);
  gtk_fixed_put (GTK_FIXED (fixed8), label6715z, 0, 496);
  gtk_widget_set_size_request (label6715z, 120, 20);

  deconnexion8 = gtk_button_new ();
  gtk_widget_show (deconnexion8);
  gtk_fixed_put (GTK_FIXED (fixed8), deconnexion8, 656, 152);
  gtk_widget_set_size_request (deconnexion8, 135, 45);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (deconnexion8), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image32 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox21), image32, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("deconnexion"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox21), label63, FALSE, FALSE, 0);

  label6687 = gtk_label_new (_("identifiant:"));
  gtk_widget_show (label6687);
  gtk_fixed_put (GTK_FIXED (fixed8), label6687, 328, 224);
  gtk_widget_set_size_request (label6687, 84, 27);

  entry2empty = gtk_entry_new ();
  gtk_widget_show (entry2empty);
  gtk_fixed_put (GTK_FIXED (fixed8), entry2empty, 440, 264);
  gtk_widget_set_size_request (entry2empty, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2empty), 8226);

  label6717 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label6717);
  gtk_fixed_put (GTK_FIXED (fixed8), label6717, 312, 272);
  gtk_widget_set_size_request (label6717, 118, 22);

  button4emp = gtk_button_new ();
  gtk_widget_show (button4emp);
  gtk_fixed_put (GTK_FIXED (fixed8), button4emp, 496, 728);
  gtk_widget_set_size_request (button4emp, 135, 45);
  gtk_button_set_focus_on_click (GTK_BUTTON (button4emp), FALSE);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button4emp), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image36 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox23), image36, FALSE, FALSE, 0);

  label6688 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label6688);
  gtk_box_pack_start (GTK_BOX (hbox23), label6688, FALSE, FALSE, 0);

  validercemp = gtk_button_new ();
  gtk_widget_show (validercemp);
  gtk_fixed_put (GTK_FIXED (fixed8), validercemp, 96, 592);
  gtk_widget_set_size_request (validercemp, 135, 45);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (validercemp), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image47 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image47);
  gtk_box_pack_start (GTK_BOX (hbox30), image47, FALSE, FALSE, 0);

  label6716 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label6716);
  gtk_box_pack_start (GTK_BOX (hbox30), label6716, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) deconnexion8, "clicked",
                    G_CALLBACK (on_deconnexion8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4emp, "clicked",
                    G_CALLBACK (on_button4emp_clicked),
                    NULL);
  g_signal_connect ((gpointer) validercemp, "clicked",
                    G_CALLBACK (on_validercemp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8, window8, "window8");
  GLADE_HOOKUP_OBJECT (window8, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window8, entry18z, "entry18z");
  GLADE_HOOKUP_OBJECT (window8, entry28z, "entry28z");
  GLADE_HOOKUP_OBJECT (window8, entry38z, "entry38z");
  GLADE_HOOKUP_OBJECT (window8, entry48z, "entry48z");
  GLADE_HOOKUP_OBJECT (window8, entry58z, "entry58z");
  GLADE_HOOKUP_OBJECT (window8, spinbutton2jours, "spinbutton2jours");
  GLADE_HOOKUP_OBJECT (window8, spinbutton3mois, "spinbutton3mois");
  GLADE_HOOKUP_OBJECT (window8, spinbutton4annee, "spinbutton4annee");
  GLADE_HOOKUP_OBJECT (window8, image33, "image33");
  GLADE_HOOKUP_OBJECT (window8, entry6z88, "entry6z88");
  GLADE_HOOKUP_OBJECT (window8, image35, "image35");
  GLADE_HOOKUP_OBJECT (window8, label758z, "label758z");
  GLADE_HOOKUP_OBJECT (window8, label698z, "label698z");
  GLADE_HOOKUP_OBJECT (window8, label688z, "label688z");
  GLADE_HOOKUP_OBJECT (window8, label7478z, "label7478z");
  GLADE_HOOKUP_OBJECT (window8, label738z, "label738z");
  GLADE_HOOKUP_OBJECT (window8, label728z, "label728z");
  GLADE_HOOKUP_OBJECT (window8, label718z, "label718z");
  GLADE_HOOKUP_OBJECT (window8, comboboxentry18z, "comboboxentry18z");
  GLADE_HOOKUP_OBJECT (window8, label708z, "label708z");
  GLADE_HOOKUP_OBJECT (window8, label678z, "label678z");
  GLADE_HOOKUP_OBJECT (window8, label65zz, "label65zz");
  GLADE_HOOKUP_OBJECT (window8, entry1emptt, "entry1emptt");
  GLADE_HOOKUP_OBJECT (window8, label6715z, "label6715z");
  GLADE_HOOKUP_OBJECT (window8, deconnexion8, "deconnexion8");
  GLADE_HOOKUP_OBJECT (window8, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window8, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window8, image32, "image32");
  GLADE_HOOKUP_OBJECT (window8, label63, "label63");
  GLADE_HOOKUP_OBJECT (window8, label6687, "label6687");
  GLADE_HOOKUP_OBJECT (window8, entry2empty, "entry2empty");
  GLADE_HOOKUP_OBJECT (window8, label6717, "label6717");
  GLADE_HOOKUP_OBJECT (window8, button4emp, "button4emp");
  GLADE_HOOKUP_OBJECT (window8, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window8, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window8, image36, "image36");
  GLADE_HOOKUP_OBJECT (window8, label6688, "label6688");
  GLADE_HOOKUP_OBJECT (window8, validercemp, "validercemp");
  GLADE_HOOKUP_OBJECT (window8, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window8, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window8, image47, "image47");
  GLADE_HOOKUP_OBJECT (window8, label6716, "label6716");

  return window8;
}

GtkWidget*
create_window9 (void)
{
  GtkWidget *window9;
  GtkWidget *fixed10;
  GtkWidget *entry6emp;
  GtkWidget *entry7emp;
  GtkWidget *entry8emp;
  GtkWidget *entry9emp;
  GtkWidget *entry10emp;
  GtkObject *spinbutton3emp_adj;
  GtkWidget *spinbutton3emp;
  GtkObject *spinbutton4emp_adj;
  GtkWidget *spinbutton4emp;
  GtkObject *spinbutton5emp_adj;
  GtkWidget *spinbutton5emp;
  GtkWidget *image41;
  GtkWidget *entry11emp;
  GtkWidget *image42;
  GtkWidget *label6711;
  GtkWidget *entry1empt;
  GtkWidget *comboboxentry1emp;
  GtkWidget *label6703;
  GtkWidget *label6709;
  GtkWidget *label6710;
  GtkWidget *label6707;
  GtkWidget *label6706;
  GtkWidget *label6708;
  GtkWidget *label6714;
  GtkWidget *entry1id7;
  GtkWidget *label6718z;
  GtkWidget *label6705;
  GtkWidget *label6704;
  GtkWidget *label6702;
  GtkWidget *label6715r;

  window9 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window9), _("window9"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window9), fixed10);

  entry6emp = gtk_entry_new ();
  gtk_widget_show (entry6emp);
  gtk_fixed_put (GTK_FIXED (fixed10), entry6emp, 456, 240);
  gtk_widget_set_size_request (entry6emp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6emp), 8226);

  entry7emp = gtk_entry_new ();
  gtk_widget_show (entry7emp);
  gtk_fixed_put (GTK_FIXED (fixed10), entry7emp, 456, 160);
  gtk_widget_set_size_request (entry7emp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7emp), 8226);

  entry8emp = gtk_entry_new ();
  gtk_widget_show (entry8emp);
  gtk_fixed_put (GTK_FIXED (fixed10), entry8emp, 456, 288);
  gtk_widget_set_size_request (entry8emp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8emp), 8226);

  entry9emp = gtk_entry_new ();
  gtk_widget_show (entry9emp);
  gtk_fixed_put (GTK_FIXED (fixed10), entry9emp, 448, 456);
  gtk_widget_set_size_request (entry9emp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9emp), 8226);

  entry10emp = gtk_entry_new ();
  gtk_widget_show (entry10emp);
  gtk_fixed_put (GTK_FIXED (fixed10), entry10emp, 448, 504);
  gtk_widget_set_size_request (entry10emp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10emp), 8226);

  spinbutton3emp_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton3emp = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3emp_adj), 1, 0);
  gtk_widget_show (spinbutton3emp);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton3emp, 432, 408);
  gtk_widget_set_size_request (spinbutton3emp, 70, 34);

  spinbutton4emp_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton4emp = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4emp_adj), 1, 0);
  gtk_widget_show (spinbutton4emp);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton4emp, 528, 408);
  gtk_widget_set_size_request (spinbutton4emp, 70, 34);

  spinbutton5emp_adj = gtk_adjustment_new (1, 1950, 2019, 1, 10, 10);
  spinbutton5emp = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5emp_adj), 1, 0);
  gtk_widget_show (spinbutton5emp);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton5emp, 616, 408);
  gtk_widget_set_size_request (spinbutton5emp, 70, 34);

  image41 = create_pixmap (window9, "p.png");
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (fixed10), image41, 0, 0);
  gtk_widget_set_size_request (image41, 805, 141);

  entry11emp = gtk_entry_new ();
  gtk_widget_show (entry11emp);
  gtk_fixed_put (GTK_FIXED (fixed10), entry11emp, 448, 544);
  gtk_widget_set_size_request (entry11emp, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11emp), 8226);

  image42 = create_pixmap (window9, "addd.png");
  gtk_widget_show (image42);
  gtk_fixed_put (GTK_FIXED (fixed10), image42, 0, 152);
  gtk_widget_set_size_request (image42, 280, 328);

  label6711 = gtk_label_new (_("adresse"));
  gtk_widget_show (label6711);
  gtk_fixed_put (GTK_FIXED (fixed10), label6711, 328, 552);
  gtk_widget_set_size_request (label6711, 78, 21);

  entry1empt = gtk_entry_new ();
  gtk_widget_show (entry1empt);
  gtk_fixed_put (GTK_FIXED (fixed10), entry1empt, 456, 200);
  gtk_widget_set_size_request (entry1empt, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1empt), 8226);

  comboboxentry1emp = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1emp);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxentry1emp, 448, 336);
  gtk_widget_set_size_request (comboboxentry1emp, 206, 34);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1emp), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1emp), _("femme"));

  label6703 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label6703);
  gtk_fixed_put (GTK_FIXED (fixed10), label6703, 312, 160);
  gtk_widget_set_size_request (label6703, 84, 27);

  label6709 = gtk_label_new (_("tel"));
  gtk_widget_show (label6709);
  gtk_fixed_put (GTK_FIXED (fixed10), label6709, 336, 464);
  gtk_widget_set_size_request (label6709, 52, 25);

  label6710 = gtk_label_new (_("email"));
  gtk_widget_show (label6710);
  gtk_fixed_put (GTK_FIXED (fixed10), label6710, 336, 512);
  gtk_widget_set_size_request (label6710, 49, 17);

  label6707 = gtk_label_new (_("mois"));
  gtk_widget_show (label6707);
  gtk_fixed_put (GTK_FIXED (fixed10), label6707, 532, 375);
  gtk_widget_set_size_request (label6707, 50, 20);

  label6706 = gtk_label_new (_("jour"));
  gtk_widget_show (label6706);
  gtk_fixed_put (GTK_FIXED (fixed10), label6706, 432, 375);
  gtk_widget_set_size_request (label6706, 50, 20);

  label6708 = gtk_label_new (_("annee"));
  gtk_widget_show (label6708);
  gtk_fixed_put (GTK_FIXED (fixed10), label6708, 632, 375);
  gtk_widget_set_size_request (label6708, 50, 20);

  label6714 = gtk_label_new (_("date de naissance"));
  gtk_widget_show (label6714);
  gtk_fixed_put (GTK_FIXED (fixed10), label6714, 296, 368);
  gtk_widget_set_size_request (label6714, 128, 30);

  entry1id7 = gtk_entry_new ();
  gtk_widget_show (entry1id7);
  gtk_fixed_put (GTK_FIXED (fixed10), entry1id7, 112, 488);
  gtk_widget_set_size_request (entry1id7, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1id7), 8226);

  label6718z = gtk_label_new (_("identifiant"));
  gtk_widget_show (label6718z);
  gtk_fixed_put (GTK_FIXED (fixed10), label6718z, 0, 496);
  gtk_widget_set_size_request (label6718z, 102, 17);

  label6705 = gtk_label_new (_("sexe"));
  gtk_widget_show (label6705);
  gtk_fixed_put (GTK_FIXED (fixed10), label6705, 304, 344);
  gtk_widget_set_size_request (label6705, 52, 25);

  label6704 = gtk_label_new (_("prenom"));
  gtk_widget_show (label6704);
  gtk_fixed_put (GTK_FIXED (fixed10), label6704, 312, 296);
  gtk_widget_set_size_request (label6704, 60, 23);

  label6702 = gtk_label_new (_("nom"));
  gtk_widget_show (label6702);
  gtk_fixed_put (GTK_FIXED (fixed10), label6702, 320, 240);
  gtk_widget_set_size_request (label6702, 66, 37);

  label6715r = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label6715r);
  gtk_fixed_put (GTK_FIXED (fixed10), label6715r, 312, 200);
  gtk_widget_set_size_request (label6715r, 112, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window9, window9, "window9");
  GLADE_HOOKUP_OBJECT (window9, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window9, entry6emp, "entry6emp");
  GLADE_HOOKUP_OBJECT (window9, entry7emp, "entry7emp");
  GLADE_HOOKUP_OBJECT (window9, entry8emp, "entry8emp");
  GLADE_HOOKUP_OBJECT (window9, entry9emp, "entry9emp");
  GLADE_HOOKUP_OBJECT (window9, entry10emp, "entry10emp");
  GLADE_HOOKUP_OBJECT (window9, spinbutton3emp, "spinbutton3emp");
  GLADE_HOOKUP_OBJECT (window9, spinbutton4emp, "spinbutton4emp");
  GLADE_HOOKUP_OBJECT (window9, spinbutton5emp, "spinbutton5emp");
  GLADE_HOOKUP_OBJECT (window9, image41, "image41");
  GLADE_HOOKUP_OBJECT (window9, entry11emp, "entry11emp");
  GLADE_HOOKUP_OBJECT (window9, image42, "image42");
  GLADE_HOOKUP_OBJECT (window9, label6711, "label6711");
  GLADE_HOOKUP_OBJECT (window9, entry1empt, "entry1empt");
  GLADE_HOOKUP_OBJECT (window9, comboboxentry1emp, "comboboxentry1emp");
  GLADE_HOOKUP_OBJECT (window9, label6703, "label6703");
  GLADE_HOOKUP_OBJECT (window9, label6709, "label6709");
  GLADE_HOOKUP_OBJECT (window9, label6710, "label6710");
  GLADE_HOOKUP_OBJECT (window9, label6707, "label6707");
  GLADE_HOOKUP_OBJECT (window9, label6706, "label6706");
  GLADE_HOOKUP_OBJECT (window9, label6708, "label6708");
  GLADE_HOOKUP_OBJECT (window9, label6714, "label6714");
  GLADE_HOOKUP_OBJECT (window9, entry1id7, "entry1id7");
  GLADE_HOOKUP_OBJECT (window9, label6718z, "label6718z");
  GLADE_HOOKUP_OBJECT (window9, label6705, "label6705");
  GLADE_HOOKUP_OBJECT (window9, label6704, "label6704");
  GLADE_HOOKUP_OBJECT (window9, label6702, "label6702");
  GLADE_HOOKUP_OBJECT (window9, label6715r, "label6715r");

  return window9;
}

