/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_reservations (void)
{
  GtkWidget *reservations;
  GtkWidget *fixed1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label4;
  GtkWidget *label3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label7;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label8;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label5;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label6;
  GtkWidget *combobox10;

  reservations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (reservations), _("reservations"));
  gtk_window_set_default_size (GTK_WINDOW (reservations), 800, 469);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (reservations), fixed1);

  image1 = create_pixmap (reservations, "interface generale.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 0);
  gtk_widget_set_size_request (image1, 800, 469);

  label1 = gtk_label_new (_("consulter mes r\303\251servations: "));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 152, 104);
  gtk_widget_set_size_request (label1, 216, 72);

  label2 = gtk_label_new (_("ajouter une r\303\251servation : "));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 160, 176);
  gtk_widget_set_size_request (label2, 200, 64);

  label4 = gtk_label_new (_("modifier une r\303\251servation:"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 136, 240);
  gtk_widget_set_size_request (label4, 240, 80);

  label3 = gtk_label_new (_("supprimer une r\303\251servation:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 136, 328);
  gtk_widget_set_size_request (label3, 240, 56);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 400, 264);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 400, 344);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 640, 256);
  gtk_widget_set_size_request (button3, 112, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 648, 344);
  gtk_widget_set_size_request (button4, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox4), label8, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 440, 120);
  gtk_widget_set_size_request (button1, 112, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("affichage"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 640, 184);
  gtk_widget_set_size_request (button2, 112, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("r\303\251server"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  combobox10 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox10);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox10, 400, 192);
  gtk_widget_set_size_request (combobox10, 168, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("vol"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("hebergement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("location de voiture"));

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reservations, reservations, "reservations");
  GLADE_HOOKUP_OBJECT (reservations, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (reservations, image1, "image1");
  GLADE_HOOKUP_OBJECT (reservations, label1, "label1");
  GLADE_HOOKUP_OBJECT (reservations, label2, "label2");
  GLADE_HOOKUP_OBJECT (reservations, label4, "label4");
  GLADE_HOOKUP_OBJECT (reservations, label3, "label3");
  GLADE_HOOKUP_OBJECT (reservations, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (reservations, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (reservations, button3, "button3");
  GLADE_HOOKUP_OBJECT (reservations, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (reservations, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (reservations, image4, "image4");
  GLADE_HOOKUP_OBJECT (reservations, label7, "label7");
  GLADE_HOOKUP_OBJECT (reservations, button4, "button4");
  GLADE_HOOKUP_OBJECT (reservations, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (reservations, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (reservations, image5, "image5");
  GLADE_HOOKUP_OBJECT (reservations, label8, "label8");
  GLADE_HOOKUP_OBJECT (reservations, button1, "button1");
  GLADE_HOOKUP_OBJECT (reservations, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (reservations, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (reservations, image2, "image2");
  GLADE_HOOKUP_OBJECT (reservations, label5, "label5");
  GLADE_HOOKUP_OBJECT (reservations, button2, "button2");
  GLADE_HOOKUP_OBJECT (reservations, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (reservations, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (reservations, image3, "image3");
  GLADE_HOOKUP_OBJECT (reservations, label6, "label6");
  GLADE_HOOKUP_OBJECT (reservations, combobox10, "combobox10");

  return reservations;
}

GtkWidget*
create_affichage (void)
{
  GtkWidget *affichage;
  GtkWidget *fixed2;
  GtkWidget *image6;
  GtkWidget *treeview1;
  GtkWidget *label9;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label11;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label10;
  GtkWidget *label57;
  GtkWidget *entry8;
  GtkWidget *button11;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image16;
  GtkWidget *label34;
  GtkWidget *label61;

  affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage), _("mes r\303\251servations"));
  gtk_window_set_default_size (GTK_WINDOW (affichage), 800, 469);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (affichage), fixed2);

  image6 = create_pixmap (affichage, "interface generale.png");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed2), image6, 0, 0);
  gtk_widget_set_size_request (image6, 800, 469);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 232, 128);
  gtk_widget_set_size_request (treeview1, 400, 216);

  label9 = gtk_label_new (_("liste des r\303\251servation "));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 328, 24);
  gtk_widget_set_size_request (label9, 200, 72);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 624, 400);
  gtk_widget_set_size_request (button6, 96, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("payer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox6), label11, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 64, 400);
  gtk_widget_set_size_request (button5, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  label57 = gtk_label_new (_("Num _res"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed2), label57, 264, 360);
  gtk_widget_set_size_request (label57, 96, 32);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed2), entry8, 360, 360);
  gtk_widget_set_size_request (entry8, 104, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed2), button11, 360, 400);
  gtk_widget_set_size_request (button11, 104, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button11), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox11), image16, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox11), label34, FALSE, FALSE, 0);

  label61 = gtk_label_new (_("<span foreground=\"blue\"><b>CIN:</b></span>"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed2), label61, 280, 80);
  gtk_widget_set_size_request (label61, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label61), TRUE);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage, affichage, "affichage");
  GLADE_HOOKUP_OBJECT (affichage, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (affichage, image6, "image6");
  GLADE_HOOKUP_OBJECT (affichage, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (affichage, label9, "label9");
  GLADE_HOOKUP_OBJECT (affichage, button6, "button6");
  GLADE_HOOKUP_OBJECT (affichage, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (affichage, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (affichage, image9, "image9");
  GLADE_HOOKUP_OBJECT (affichage, label11, "label11");
  GLADE_HOOKUP_OBJECT (affichage, button5, "button5");
  GLADE_HOOKUP_OBJECT (affichage, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (affichage, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (affichage, image7, "image7");
  GLADE_HOOKUP_OBJECT (affichage, label10, "label10");
  GLADE_HOOKUP_OBJECT (affichage, label57, "label57");
  GLADE_HOOKUP_OBJECT (affichage, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (affichage, button11, "button11");
  GLADE_HOOKUP_OBJECT (affichage, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (affichage, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (affichage, image16, "image16");
  GLADE_HOOKUP_OBJECT (affichage, label34, "label34");
  GLADE_HOOKUP_OBJECT (affichage, label61, "label61");

  return affichage;
}

GtkWidget*
create_vol (void)
{
  GtkWidget *vol;
  GtkWidget *notebook1;
  GtkWidget *fixed4;
  GtkWidget *image11;
  GtkWidget *entry5;
  GtkWidget *entry7;
  GtkObject *spinbuttonadulte_adj;
  GtkWidget *spinbuttonadulte;
  GtkObject *spinbuttonenfant_adj;
  GtkWidget *spinbuttonenfant;
  GtkObject *spinbuttonbebe_adj;
  GtkWidget *spinbuttonbebe;
  GtkWidget *combobox7;
  GtkWidget *combobox9;
  GtkWidget *combobox11;
  GtkWidget *retour_vol;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image15;
  GtkWidget *label32;
  GtkWidget *button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image13;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label28;
  GtkWidget *valider;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image27;
  GtkWidget *label50;
  GtkWidget *label47;
  GtkWidget *label29;
  GtkWidget *valider_date;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image28;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *devis_vol;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image14;
  GtkWidget *label31;
  GtkWidget *first;
  GtkWidget *business;
  GtkWidget *economique;
  GtkWidget *label30;
  GtkWidget *label33;
  GtkWidget *image17;
  GtkWidget *image18;
  GtkWidget *image19;
  GtkWidget *label65;
  GtkWidget *reessayervol;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image33;
  GtkWidget *label60;
  GtkWidget *enregistrementvol;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image34;
  GtkWidget *label64;
  GtkWidget *label21;

  vol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (vol), _("reservation vol"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (vol), notebook1);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  image11 = create_pixmap (vol, "interface generale.png");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed4), image11, 0, 0);
  gtk_widget_set_size_request (image11, 808, 464);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 264, 40);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 464, 40);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  spinbuttonadulte_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbuttonadulte = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonadulte_adj), 1, 0);
  gtk_widget_show (spinbuttonadulte);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonadulte, 200, 304);
  gtk_widget_set_size_request (spinbuttonadulte, 60, 27);

  spinbuttonenfant_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbuttonenfant = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonenfant_adj), 1, 0);
  gtk_widget_show (spinbuttonenfant);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonenfant, 304, 304);
  gtk_widget_set_size_request (spinbuttonenfant, 60, 27);

  spinbuttonbebe_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbuttonbebe = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonbebe_adj), 1, 0);
  gtk_widget_show (spinbuttonbebe);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonbebe, 408, 304);
  gtk_widget_set_size_request (spinbuttonbebe, 60, 27);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox7, 285, 117);
  gtk_widget_set_size_request (combobox7, 326, 31);

  combobox9 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox9);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox9, 138, 174);
  gtk_widget_set_size_request (combobox9, 178, 31);

  combobox11 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox11);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox11, 586, 176);
  gtk_widget_set_size_request (combobox11, 186, 31);

  retour_vol = gtk_button_new ();
  gtk_widget_show (retour_vol);
  gtk_fixed_put (GTK_FIXED (fixed4), retour_vol, 16, 424);
  gtk_widget_set_size_request (retour_vol, 88, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (retour_vol), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox10), image15, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox10), label32, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed4), button8, 672, 32);
  gtk_widget_set_size_request (button8, 112, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox8), image13, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("recherche"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox8), label23, FALSE, FALSE, 0);

  label24 = gtk_label_new (_("<b>Ville de d\303\251part:</b>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 280, 0);
  gtk_widget_set_size_request (label24, 136, 40);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<b>Ville d'arriv\303\251e:</b>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 480, 0);
  gtk_widget_set_size_request (label25, 112, 40);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label28 = gtk_label_new (_("<span foreground=\"blue\">b</span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed4), label28, 184, 72);
  gtk_widget_set_size_request (label28, 600, 40);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  valider = gtk_button_new ();
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed4), valider, 672, 112);
  gtk_widget_set_size_request (valider, 112, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (valider), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image27 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox15), image27, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox15), label50, FALSE, FALSE, 0);

  label47 = gtk_label_new (_("<b>Compagnie:</b>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed4), label47, 152, 112);
  gtk_widget_set_size_request (label47, 104, 40);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  label29 = gtk_label_new (_("<b>Date d'aller:</b>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 0, 168);
  gtk_widget_set_size_request (label29, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  valider_date = gtk_button_new ();
  gtk_widget_show (valider_date);
  gtk_fixed_put (GTK_FIXED (fixed4), valider_date, 344, 176);
  gtk_widget_set_size_request (valider_date, 88, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (valider_date), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image28 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox16), image28, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox16), label51, FALSE, FALSE, 0);

  label52 = gtk_label_new (_("<b>Date de retour:</b>"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed4), label52, 440, 176);
  gtk_widget_set_size_request (label52, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  label62 = gtk_label_new ("");
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed4), label62, 296, 416);
  gtk_widget_set_size_request (label62, 184, 48);

  label63 = gtk_label_new (_("<span foreground=\"red\"><b>le total \303\240 payer en dinars est: </b></span>"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed4), label63, 232, 376);
  gtk_widget_set_size_request (label63, 304, 48);
  gtk_label_set_use_markup (GTK_LABEL (label63), TRUE);

  devis_vol = gtk_button_new ();
  gtk_widget_show (devis_vol);
  gtk_fixed_put (GTK_FIXED (fixed4), devis_vol, 336, 344);
  gtk_widget_set_size_request (devis_vol, 96, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (devis_vol), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image14 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox9), image14, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Devis"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox9), label31, FALSE, FALSE, 0);

  first = gtk_check_button_new_with_mnemonic (_("First"));
  gtk_widget_show (first);
  gtk_fixed_put (GTK_FIXED (fixed4), first, 536, 232);
  gtk_widget_set_size_request (first, 118, 24);

  business = gtk_check_button_new_with_mnemonic (_("Business"));
  gtk_widget_show (business);
  gtk_fixed_put (GTK_FIXED (fixed4), business, 392, 232);
  gtk_widget_set_size_request (business, 118, 24);

  economique = gtk_check_button_new_with_mnemonic (_("Economique"));
  gtk_widget_show (economique);
  gtk_fixed_put (GTK_FIXED (fixed4), economique, 240, 232);
  gtk_widget_set_size_request (economique, 118, 24);

  label30 = gtk_label_new (_("<b>Classe:</b>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 136, 224);
  gtk_widget_set_size_request (label30, 80, 40);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label33 = gtk_label_new (_("<b>Nombre voyageurs:</b>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 0, 296);
  gtk_widget_set_size_request (label33, 152, 40);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  image17 = create_pixmap (vol, "Calque 3.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed4), image17, 160, 280);
  gtk_widget_set_size_request (image17, 24, 80);

  image18 = create_pixmap (vol, "Calque 2.png");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed4), image18, 264, 296);
  gtk_widget_set_size_request (image18, 24, 56);

  image19 = create_pixmap (vol, "Calque 1.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed4), image19, 368, 304);
  gtk_widget_set_size_request (image19, 32, 40);

  label65 = gtk_label_new ("");
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed4), label65, 552, 264);
  gtk_widget_set_size_request (label65, 232, 136);

  reessayervol = gtk_button_new ();
  gtk_widget_show (reessayervol);
  gtk_fixed_put (GTK_FIXED (fixed4), reessayervol, 704, 424);
  gtk_widget_set_size_request (reessayervol, 96, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (reessayervol), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image33 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox20), image33, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("r\303\251essayer"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox20), label60, FALSE, FALSE, 0);

  enregistrementvol = gtk_button_new ();
  gtk_widget_show (enregistrementvol);
  gtk_fixed_put (GTK_FIXED (fixed4), enregistrementvol, 584, 424);
  gtk_widget_set_size_request (enregistrementvol, 112, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (enregistrementvol), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image34 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox21), image34, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("enregistrer"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox21), label64, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("aller -retour"));
  gtk_widget_show (label21);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label21);

  g_signal_connect ((gpointer) retour_vol, "clicked",
                    G_CALLBACK (on_retour_vol_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) valider_date, "clicked",
                    G_CALLBACK (on_valider_date_clicked),
                    NULL);
  g_signal_connect ((gpointer) devis_vol, "clicked",
                    G_CALLBACK (on_devis_vol_clicked),
                    NULL);
  g_signal_connect ((gpointer) reessayervol, "clicked",
                    G_CALLBACK (on_reessayervol_clicked),
                    NULL);
  g_signal_connect ((gpointer) enregistrementvol, "clicked",
                    G_CALLBACK (on_enregistrementvol_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (vol, vol, "vol");
  GLADE_HOOKUP_OBJECT (vol, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (vol, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (vol, image11, "image11");
  GLADE_HOOKUP_OBJECT (vol, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (vol, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (vol, spinbuttonadulte, "spinbuttonadulte");
  GLADE_HOOKUP_OBJECT (vol, spinbuttonenfant, "spinbuttonenfant");
  GLADE_HOOKUP_OBJECT (vol, spinbuttonbebe, "spinbuttonbebe");
  GLADE_HOOKUP_OBJECT (vol, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (vol, combobox9, "combobox9");
  GLADE_HOOKUP_OBJECT (vol, combobox11, "combobox11");
  GLADE_HOOKUP_OBJECT (vol, retour_vol, "retour_vol");
  GLADE_HOOKUP_OBJECT (vol, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (vol, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (vol, image15, "image15");
  GLADE_HOOKUP_OBJECT (vol, label32, "label32");
  GLADE_HOOKUP_OBJECT (vol, button8, "button8");
  GLADE_HOOKUP_OBJECT (vol, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (vol, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (vol, image13, "image13");
  GLADE_HOOKUP_OBJECT (vol, label23, "label23");
  GLADE_HOOKUP_OBJECT (vol, label24, "label24");
  GLADE_HOOKUP_OBJECT (vol, label25, "label25");
  GLADE_HOOKUP_OBJECT (vol, label28, "label28");
  GLADE_HOOKUP_OBJECT (vol, valider, "valider");
  GLADE_HOOKUP_OBJECT (vol, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (vol, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (vol, image27, "image27");
  GLADE_HOOKUP_OBJECT (vol, label50, "label50");
  GLADE_HOOKUP_OBJECT (vol, label47, "label47");
  GLADE_HOOKUP_OBJECT (vol, label29, "label29");
  GLADE_HOOKUP_OBJECT (vol, valider_date, "valider_date");
  GLADE_HOOKUP_OBJECT (vol, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (vol, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (vol, image28, "image28");
  GLADE_HOOKUP_OBJECT (vol, label51, "label51");
  GLADE_HOOKUP_OBJECT (vol, label52, "label52");
  GLADE_HOOKUP_OBJECT (vol, label62, "label62");
  GLADE_HOOKUP_OBJECT (vol, label63, "label63");
  GLADE_HOOKUP_OBJECT (vol, devis_vol, "devis_vol");
  GLADE_HOOKUP_OBJECT (vol, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (vol, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (vol, image14, "image14");
  GLADE_HOOKUP_OBJECT (vol, label31, "label31");
  GLADE_HOOKUP_OBJECT (vol, first, "first");
  GLADE_HOOKUP_OBJECT (vol, business, "business");
  GLADE_HOOKUP_OBJECT (vol, economique, "economique");
  GLADE_HOOKUP_OBJECT (vol, label30, "label30");
  GLADE_HOOKUP_OBJECT (vol, label33, "label33");
  GLADE_HOOKUP_OBJECT (vol, image17, "image17");
  GLADE_HOOKUP_OBJECT (vol, image18, "image18");
  GLADE_HOOKUP_OBJECT (vol, image19, "image19");
  GLADE_HOOKUP_OBJECT (vol, label65, "label65");
  GLADE_HOOKUP_OBJECT (vol, reessayervol, "reessayervol");
  GLADE_HOOKUP_OBJECT (vol, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (vol, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (vol, image33, "image33");
  GLADE_HOOKUP_OBJECT (vol, label60, "label60");
  GLADE_HOOKUP_OBJECT (vol, enregistrementvol, "enregistrementvol");
  GLADE_HOOKUP_OBJECT (vol, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (vol, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (vol, image34, "image34");
  GLADE_HOOKUP_OBJECT (vol, label64, "label64");
  GLADE_HOOKUP_OBJECT (vol, label21, "label21");

  return vol;
}

