/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestionfacture (void)
{
  GtkWidget *gestionfacture;
  GtkWidget *fixed1brody;
  GtkWidget *notebook1brody;
  GtkWidget *fixed2brody;
  GtkWidget *treeview1brody;
  GtkWidget *afficherbrody;
  GtkWidget *label1brody;
  GtkWidget *fixed3brody;
  GtkWidget *entry2brody;
  GtkWidget *entry3brody;
  GtkWidget *entry4brody;
  GtkWidget *entry5brody;
  GtkWidget *entry6brody;
  GtkObject *spinbutton1brody_adj;
  GtkWidget *spinbutton1brody;
  GtkObject *spinbutton2brody_adj;
  GtkWidget *spinbutton2brody;
  GtkObject *spinbutton3brody_adj;
  GtkWidget *spinbutton3brody;
  GtkWidget *comboboxentry1brody;
  GtkWidget *label11brody;
  GtkWidget *label5brody;
  GtkWidget *label6brody;
  GtkWidget *label7brody;
  GtkWidget *label8brody;
  GtkWidget *label9brody;
  GtkWidget *label10brody;
  GtkWidget *label12brody;
  GtkWidget *label13brody;
  GtkWidget *label14brody;
  GtkWidget *modifierbrody;
  GtkWidget *label2brody;
  GtkWidget *fixed4brody;
  GtkWidget *entry1brody;
  GtkWidget *label4brody;
  GtkWidget *supprimerbrody;
  GtkWidget *label3brody;

  gestionfacture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestionfacture), _("GESTION DES FACTURES"));

  fixed1brody = gtk_fixed_new ();
  gtk_widget_show (fixed1brody);
  gtk_container_add (GTK_CONTAINER (gestionfacture), fixed1brody);

  notebook1brody = gtk_notebook_new ();
  gtk_widget_show (notebook1brody);
  gtk_fixed_put (GTK_FIXED (fixed1brody), notebook1brody, 0, 64);
  gtk_widget_set_size_request (notebook1brody, 672, 328);

  fixed2brody = gtk_fixed_new ();
  gtk_widget_show (fixed2brody);
  gtk_container_add (GTK_CONTAINER (notebook1brody), fixed2brody);

  treeview1brody = gtk_tree_view_new ();
  gtk_widget_show (treeview1brody);
  gtk_fixed_put (GTK_FIXED (fixed2brody), treeview1brody, 0, 0);
  gtk_widget_set_size_request (treeview1brody, 664, 216);

  afficherbrody = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (afficherbrody);
  gtk_fixed_put (GTK_FIXED (fixed2brody), afficherbrody, 264, 248);
  gtk_widget_set_size_request (afficherbrody, 80, 32);

  label1brody = gtk_label_new (_("Afficher"));
  gtk_widget_show (label1brody);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1brody), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1brody), 0), label1brody);

  fixed3brody = gtk_fixed_new ();
  gtk_widget_show (fixed3brody);
  gtk_container_add (GTK_CONTAINER (notebook1brody), fixed3brody);

  entry2brody = gtk_entry_new ();
  gtk_widget_show (entry2brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), entry2brody, 96, 8);
  gtk_widget_set_size_request (entry2brody, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2brody), 8226);

  entry3brody = gtk_entry_new ();
  gtk_widget_show (entry3brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), entry3brody, 96, 40);
  gtk_widget_set_size_request (entry3brody, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3brody), 8226);

  entry4brody = gtk_entry_new ();
  gtk_widget_show (entry4brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), entry4brody, 96, 72);
  gtk_widget_set_size_request (entry4brody, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4brody), 8226);

  entry5brody = gtk_entry_new ();
  gtk_widget_show (entry5brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), entry5brody, 96, 104);
  gtk_widget_set_size_request (entry5brody, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5brody), 8226);

  entry6brody = gtk_entry_new ();
  gtk_widget_show (entry6brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), entry6brody, 96, 184);
  gtk_widget_set_size_request (entry6brody, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6brody), 8226);

  spinbutton1brody_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1brody = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1brody_adj), 1, 0);
  gtk_widget_show (spinbutton1brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), spinbutton1brody, 40, 248);
  gtk_widget_set_size_request (spinbutton1brody, 60, 27);

  spinbutton2brody_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2brody = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2brody_adj), 1, 0);
  gtk_widget_show (spinbutton2brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), spinbutton2brody, 144, 248);
  gtk_widget_set_size_request (spinbutton2brody, 60, 27);

  spinbutton3brody_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3brody = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3brody_adj), 1, 0);
  gtk_widget_show (spinbutton3brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), spinbutton3brody, 232, 248);
  gtk_widget_set_size_request (spinbutton3brody, 60, 27);

  comboboxentry1brody = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), comboboxentry1brody, 96, 144);
  gtk_widget_set_size_request (comboboxentry1brody, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1brody), _("Hotel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1brody), _("Reservation_vol"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1brody), _("Location_vehicule"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1brody), _("Restaurant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1brody), _("Excurtion"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1brody), _("Autres"));

  label11brody = gtk_label_new (_("DATE"));
  gtk_widget_show (label11brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label11brody, 144, 216);
  gtk_widget_set_size_request (label11brody, 49, 17);

  label5brody = gtk_label_new (_("ID FACTURE"));
  gtk_widget_show (label5brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label5brody, 0, 16);
  gtk_widget_set_size_request (label5brody, 88, 16);

  label6brody = gtk_label_new (_("ID CLIENT"));
  gtk_widget_show (label6brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label6brody, 8, 48);
  gtk_widget_set_size_request (label6brody, 80, 16);

  label7brody = gtk_label_new (_("NOM"));
  gtk_widget_show (label7brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label7brody, 48, 80);
  gtk_widget_set_size_request (label7brody, 41, 17);

  label8brody = gtk_label_new (_("PRENOM"));
  gtk_widget_show (label8brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label8brody, 16, 112);
  gtk_widget_set_size_request (label8brody, 72, 16);

  label9brody = gtk_label_new (_("SERVICE"));
  gtk_widget_show (label9brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label9brody, 16, 152);
  gtk_widget_set_size_request (label9brody, 64, 16);

  label10brody = gtk_label_new (_("PRIX"));
  gtk_widget_show (label10brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label10brody, 32, 192);
  gtk_widget_set_size_request (label10brody, 49, 17);

  label12brody = gtk_label_new (_("J"));
  gtk_widget_show (label12brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label12brody, 0, 256);
  gtk_widget_set_size_request (label12brody, 49, 17);

  label13brody = gtk_label_new (_("M"));
  gtk_widget_show (label13brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label13brody, 96, 256);
  gtk_widget_set_size_request (label13brody, 49, 17);

  label14brody = gtk_label_new (_("A"));
  gtk_widget_show (label14brody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), label14brody, 192, 256);
  gtk_widget_set_size_request (label14brody, 49, 17);

  modifierbrody = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (modifierbrody);
  gtk_fixed_put (GTK_FIXED (fixed3brody), modifierbrody, 312, 8);
  gtk_widget_set_size_request (modifierbrody, 88, 32);

  label2brody = gtk_label_new (_("Modifier"));
  gtk_widget_show (label2brody);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1brody), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1brody), 1), label2brody);

  fixed4brody = gtk_fixed_new ();
  gtk_widget_show (fixed4brody);
  gtk_container_add (GTK_CONTAINER (notebook1brody), fixed4brody);

  entry1brody = gtk_entry_new ();
  gtk_widget_show (entry1brody);
  gtk_fixed_put (GTK_FIXED (fixed4brody), entry1brody, 120, 88);
  gtk_widget_set_size_request (entry1brody, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1brody), 8226);

  label4brody = gtk_label_new (_("ID FACTURE"));
  gtk_widget_show (label4brody);
  gtk_fixed_put (GTK_FIXED (fixed4brody), label4brody, 32, 88);
  gtk_widget_set_size_request (label4brody, 88, 32);

  supprimerbrody = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (supprimerbrody);
  gtk_fixed_put (GTK_FIXED (fixed4brody), supprimerbrody, 152, 136);
  gtk_widget_set_size_request (supprimerbrody, 88, 32);

  label3brody = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label3brody);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1brody), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1brody), 2), label3brody);

  g_signal_connect ((gpointer) afficherbrody, "clicked",
                    G_CALLBACK (on_afficherbrody_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierbrody, "clicked",
                    G_CALLBACK (on_modifierbrody_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimerbrody, "clicked",
                    G_CALLBACK (on_supprimerbrody_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestionfacture, gestionfacture, "gestionfacture");
  GLADE_HOOKUP_OBJECT (gestionfacture, fixed1brody, "fixed1brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, notebook1brody, "notebook1brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, fixed2brody, "fixed2brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, treeview1brody, "treeview1brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, afficherbrody, "afficherbrody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label1brody, "label1brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, fixed3brody, "fixed3brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, entry2brody, "entry2brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, entry3brody, "entry3brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, entry4brody, "entry4brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, entry5brody, "entry5brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, entry6brody, "entry6brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, spinbutton1brody, "spinbutton1brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, spinbutton2brody, "spinbutton2brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, spinbutton3brody, "spinbutton3brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, comboboxentry1brody, "comboboxentry1brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label11brody, "label11brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label5brody, "label5brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label6brody, "label6brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label7brody, "label7brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label8brody, "label8brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label9brody, "label9brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label10brody, "label10brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label12brody, "label12brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label13brody, "label13brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label14brody, "label14brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, modifierbrody, "modifierbrody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label2brody, "label2brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, fixed4brody, "fixed4brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, entry1brody, "entry1brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label4brody, "label4brody");
  GLADE_HOOKUP_OBJECT (gestionfacture, supprimerbrody, "supprimerbrody");
  GLADE_HOOKUP_OBJECT (gestionfacture, label3brody, "label3brody");

  return gestionfacture;
}

