/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_voiture (void)
{
  GtkWidget *gestion_voiture;
  GtkWidget *fixed1;
  GtkWidget *image1;
  GtkWidget *afficherlesvoitures;
  GtkWidget *ajouterunevoitureb;

  gestion_voiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_voiture), _("Gestion des voitures"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion_voiture), fixed1);

  image1 = create_pixmap (gestion_voiture, "location-voiture-pas-cher.jpg");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 0);
  gtk_widget_set_size_request (image1, 552, 424);

  afficherlesvoitures = gtk_button_new_with_mnemonic (_("Afficher les voitures"));
  gtk_widget_show (afficherlesvoitures);
  gtk_fixed_put (GTK_FIXED (fixed1), afficherlesvoitures, 192, 352);
  gtk_widget_set_size_request (afficherlesvoitures, 192, 56);

  ajouterunevoitureb = gtk_button_new_with_mnemonic (_("ajouter une voiture"));
  gtk_widget_show (ajouterunevoitureb);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouterunevoitureb, 192, 280);
  gtk_widget_set_size_request (ajouterunevoitureb, 192, 56);

  g_signal_connect ((gpointer) afficherlesvoitures, "clicked",
                    G_CALLBACK (on_afficherlesvoitures_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterunevoitureb, "clicked",
                    G_CALLBACK (on_ajouterunevoitureb_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_voiture, gestion_voiture, "gestion_voiture");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestion_voiture, afficherlesvoitures, "afficherlesvoitures");
  GLADE_HOOKUP_OBJECT (gestion_voiture, ajouterunevoitureb, "ajouterunevoitureb");

  return gestion_voiture;
}

GtkWidget*
create_ajouter_une_voiture (void)
{
  GtkWidget *ajouter_une_voiture;
  GtkWidget *fixed2;
  GtkWidget *image2;
  GtkWidget *cellview8;
  GdkColor cellview8_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *cellview1;
  GdkColor cellview1_bg_color = { 0, 64836, 64836, 64836 };
  GtkWidget *cellview5;
  GdkColor cellview5_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *cellview2;
  GdkColor cellview2_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *cellview6;
  GdkColor cellview6_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *cellview7;
  GdkColor cellview7_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *label1k;
  GtkWidget *label2k;
  GtkWidget *label3k;
  GtkWidget *label4k;
  GtkWidget *label5k;
  GtkWidget *entrymarque_voiture;
  GtkWidget *label6k;
  GtkWidget *entryserie_voiture;
  GtkWidget *entryage_voiture;
  GtkWidget *entrykilometrage_voiture;
  GtkWidget *entryprix_voiture;
  GtkWidget *entrydate_voiture;
  GtkWidget *label7k;
  GtkWidget *valider;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label11;
  GtkWidget *retourgestion;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label12;
  GtkWidget *errr1;
  GtkWidget *errr2;
  GtkWidget *errr3;
  GtkWidget *errr4;
  GtkWidget *errr5;
  GtkWidget *errr6;

  ajouter_une_voiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_une_voiture), _("ajouter une voiture"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajouter_une_voiture), fixed2);

  image2 = create_pixmap (ajouter_une_voiture, "ob_888a26_rent-a-car-tunisia.jpg");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed2), image2, 0, 0);
  gtk_widget_set_size_request (image2, 552, 424);

  cellview8 = gtk_cell_view_new ();
  gtk_widget_show (cellview8);
  gtk_fixed_put (GTK_FIXED (fixed2), cellview8, 32, 64);
  gtk_widget_set_size_request (cellview8, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview8), &cellview8_bg_color);

  cellview1 = gtk_cell_view_new ();
  gtk_widget_show (cellview1);
  gtk_fixed_put (GTK_FIXED (fixed2), cellview1, 32, 112);
  gtk_widget_set_size_request (cellview1, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview1), &cellview1_bg_color);

  cellview5 = gtk_cell_view_new ();
  gtk_widget_show (cellview5);
  gtk_fixed_put (GTK_FIXED (fixed2), cellview5, 32, 160);
  gtk_widget_set_size_request (cellview5, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview5), &cellview5_bg_color);

  cellview2 = gtk_cell_view_new ();
  gtk_widget_show (cellview2);
  gtk_fixed_put (GTK_FIXED (fixed2), cellview2, 32, 208);
  gtk_widget_set_size_request (cellview2, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview2), &cellview2_bg_color);

  cellview6 = gtk_cell_view_new ();
  gtk_widget_show (cellview6);
  gtk_fixed_put (GTK_FIXED (fixed2), cellview6, 32, 256);
  gtk_widget_set_size_request (cellview6, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview6), &cellview6_bg_color);

  cellview7 = gtk_cell_view_new ();
  gtk_widget_show (cellview7);
  gtk_fixed_put (GTK_FIXED (fixed2), cellview7, 32, 304);
  gtk_widget_set_size_request (cellview7, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview7), &cellview7_bg_color);

  label1k = gtk_label_new (_("Marque :"));
  gtk_widget_show (label1k);
  gtk_fixed_put (GTK_FIXED (fixed2), label1k, 24, 64);
  gtk_widget_set_size_request (label1k, 128, 40);

  label2k = gtk_label_new (_("num de s\303\251rie :"));
  gtk_widget_show (label2k);
  gtk_fixed_put (GTK_FIXED (fixed2), label2k, 40, 112);
  gtk_widget_set_size_request (label2k, 96, 40);

  label3k = gtk_label_new (_("Age :"));
  gtk_widget_show (label3k);
  gtk_fixed_put (GTK_FIXED (fixed2), label3k, 64, 168);
  gtk_widget_set_size_request (label3k, 48, 24);

  label4k = gtk_label_new (_("Kilom\303\251trage :"));
  gtk_widget_show (label4k);
  gtk_fixed_put (GTK_FIXED (fixed2), label4k, 40, 208);
  gtk_widget_set_size_request (label4k, 96, 40);

  label5k = gtk_label_new (_("prix par jour :"));
  gtk_widget_show (label5k);
  gtk_fixed_put (GTK_FIXED (fixed2), label5k, 24, 256);
  gtk_widget_set_size_request (label5k, 120, 40);

  entrymarque_voiture = gtk_entry_new ();
  gtk_widget_show (entrymarque_voiture);
  gtk_fixed_put (GTK_FIXED (fixed2), entrymarque_voiture, 152, 64);
  gtk_widget_set_size_request (entrymarque_voiture, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymarque_voiture), 8226);

  label6k = gtk_label_new (_("Date :"));
  gtk_widget_show (label6k);
  gtk_fixed_put (GTK_FIXED (fixed2), label6k, 48, 312);
  gtk_widget_set_size_request (label6k, 72, 32);

  entryserie_voiture = gtk_entry_new ();
  gtk_widget_show (entryserie_voiture);
  gtk_fixed_put (GTK_FIXED (fixed2), entryserie_voiture, 152, 112);
  gtk_widget_set_size_request (entryserie_voiture, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryserie_voiture), 8226);

  entryage_voiture = gtk_entry_new ();
  gtk_widget_show (entryage_voiture);
  gtk_fixed_put (GTK_FIXED (fixed2), entryage_voiture, 152, 168);
  gtk_widget_set_size_request (entryage_voiture, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryage_voiture), 8226);

  entrykilometrage_voiture = gtk_entry_new ();
  gtk_widget_show (entrykilometrage_voiture);
  gtk_fixed_put (GTK_FIXED (fixed2), entrykilometrage_voiture, 152, 216);
  gtk_widget_set_size_request (entrykilometrage_voiture, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrykilometrage_voiture), 8226);

  entryprix_voiture = gtk_entry_new ();
  gtk_widget_show (entryprix_voiture);
  gtk_fixed_put (GTK_FIXED (fixed2), entryprix_voiture, 152, 264);
  gtk_widget_set_size_request (entryprix_voiture, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprix_voiture), 8226);

  entrydate_voiture = gtk_entry_new ();
  gtk_widget_show (entrydate_voiture);
  gtk_fixed_put (GTK_FIXED (fixed2), entrydate_voiture, 152, 312);
  gtk_widget_set_size_request (entrydate_voiture, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydate_voiture), 8226);

  label7k = gtk_label_new ("");
  gtk_widget_show (label7k);
  gtk_fixed_put (GTK_FIXED (fixed2), label7k, 176, 352);
  gtk_widget_set_size_request (label7k, 176, 72);

  valider = gtk_button_new ();
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed2), valider, 48, 360);
  gtk_widget_set_size_request (valider, 136, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (valider), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  retourgestion = gtk_button_new ();
  gtk_widget_show (retourgestion);
  gtk_fixed_put (GTK_FIXED (fixed2), retourgestion, 344, 360);
  gtk_widget_set_size_request (retourgestion, 136, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (retourgestion), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox4), label12, FALSE, FALSE, 0);

  errr1 = gtk_label_new ("");
  gtk_widget_show (errr1);
  gtk_fixed_put (GTK_FIXED (fixed2), errr1, 352, 64);
  gtk_widget_set_size_request (errr1, 200, 32);

  errr2 = gtk_label_new ("");
  gtk_widget_show (errr2);
  gtk_fixed_put (GTK_FIXED (fixed2), errr2, 352, 112);
  gtk_widget_set_size_request (errr2, 200, 32);

  errr3 = gtk_label_new ("");
  gtk_widget_show (errr3);
  gtk_fixed_put (GTK_FIXED (fixed2), errr3, 352, 168);
  gtk_widget_set_size_request (errr3, 200, 32);

  errr4 = gtk_label_new ("");
  gtk_widget_show (errr4);
  gtk_fixed_put (GTK_FIXED (fixed2), errr4, 352, 216);
  gtk_widget_set_size_request (errr4, 200, 32);

  errr5 = gtk_label_new ("");
  gtk_widget_show (errr5);
  gtk_fixed_put (GTK_FIXED (fixed2), errr5, 352, 264);
  gtk_widget_set_size_request (errr5, 200, 32);

  errr6 = gtk_label_new ("");
  gtk_widget_show (errr6);
  gtk_fixed_put (GTK_FIXED (fixed2), errr6, 352, 312);
  gtk_widget_set_size_request (errr6, 200, 32);

  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourgestion, "clicked",
                    G_CALLBACK (on_retourgestion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_une_voiture, ajouter_une_voiture, "ajouter_une_voiture");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, cellview8, "cellview8");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, cellview1, "cellview1");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, cellview5, "cellview5");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, cellview2, "cellview2");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, cellview6, "cellview6");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, cellview7, "cellview7");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, label1k, "label1k");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, label2k, "label2k");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, label3k, "label3k");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, label4k, "label4k");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, label5k, "label5k");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, entrymarque_voiture, "entrymarque_voiture");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, label6k, "label6k");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, entryserie_voiture, "entryserie_voiture");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, entryage_voiture, "entryage_voiture");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, entrykilometrage_voiture, "entrykilometrage_voiture");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, entryprix_voiture, "entryprix_voiture");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, entrydate_voiture, "entrydate_voiture");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, label7k, "label7k");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, valider, "valider");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, image5, "image5");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, label11, "label11");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, retourgestion, "retourgestion");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, image6, "image6");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, errr1, "errr1");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, errr2, "errr2");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, errr3, "errr3");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, errr4, "errr4");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, errr5, "errr5");
  GLADE_HOOKUP_OBJECT (ajouter_une_voiture, errr6, "errr6");

  return ajouter_une_voiture;
}

GtkWidget*
create_liste_voiture (void)
{
  GtkWidget *liste_voiture;
  GtkWidget *fixed3;
  GtkWidget *entry_supprimer_voiture;
  GtkWidget *supprimer_voiture;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image4;
  GtkWidget *label10;
  GtkWidget *refresh1;
  GtkWidget *image7;
  GtkWidget *label8k;
  GtkWidget *retourajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image3;
  GtkWidget *label9;
  GtkWidget *modifierunevoiture;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image13;
  GtkWidget *label24;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeviewvoiture;

  liste_voiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (liste_voiture), _("Liste des voitures"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (liste_voiture), fixed3);

  entry_supprimer_voiture = gtk_entry_new ();
  gtk_widget_show (entry_supprimer_voiture);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_supprimer_voiture, 208, 280);
  gtk_widget_set_size_request (entry_supprimer_voiture, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_supprimer_voiture), 8226);

  supprimer_voiture = gtk_button_new ();
  gtk_widget_show (supprimer_voiture);
  gtk_fixed_put (GTK_FIXED (fixed3), supprimer_voiture, 8, 352);
  gtk_widget_set_size_request (supprimer_voiture, 160, 56);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (supprimer_voiture), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox2), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox2), label10, FALSE, FALSE, 0);

  refresh1 = gtk_button_new ();
  gtk_widget_show (refresh1);
  gtk_fixed_put (GTK_FIXED (fixed3), refresh1, 376, 280);
  gtk_widget_set_size_request (refresh1, 40, 32);

  image7 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (refresh1), image7);

  label8k = gtk_label_new (_("num de serie de\nvoiture :"));
  gtk_widget_show (label8k);
  gtk_fixed_put (GTK_FIXED (fixed3), label8k, 32, 264);
  gtk_widget_set_size_request (label8k, 144, 56);

  retourajouter = gtk_button_new ();
  gtk_widget_show (retourajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), retourajouter, 368, 352);
  gtk_widget_set_size_request (retourajouter, 160, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (retourajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox1), image3, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox1), label9, FALSE, FALSE, 0);

  modifierunevoiture = gtk_button_new ();
  gtk_widget_show (modifierunevoiture);
  gtk_fixed_put (GTK_FIXED (fixed3), modifierunevoiture, 192, 352);
  gtk_widget_set_size_request (modifierunevoiture, 160, 56);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (modifierunevoiture), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image13 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox8), image13, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox8), label24, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow1, 8, 8);
  gtk_widget_set_size_request (scrolledwindow1, 544, 248);

  treeviewvoiture = gtk_tree_view_new ();
  gtk_widget_show (treeviewvoiture);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeviewvoiture);
  gtk_widget_set_size_request (treeviewvoiture, 544, 248);

  g_signal_connect ((gpointer) supprimer_voiture, "clicked",
                    G_CALLBACK (on_supprimer_voiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh1, "clicked",
                    G_CALLBACK (on_refresh1_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourajouter, "clicked",
                    G_CALLBACK (on_retourajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierunevoiture, "clicked",
                    G_CALLBACK (on_modifierunevoiture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_voiture, liste_voiture, "liste_voiture");
  GLADE_HOOKUP_OBJECT (liste_voiture, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (liste_voiture, entry_supprimer_voiture, "entry_supprimer_voiture");
  GLADE_HOOKUP_OBJECT (liste_voiture, supprimer_voiture, "supprimer_voiture");
  GLADE_HOOKUP_OBJECT (liste_voiture, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (liste_voiture, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (liste_voiture, image4, "image4");
  GLADE_HOOKUP_OBJECT (liste_voiture, label10, "label10");
  GLADE_HOOKUP_OBJECT (liste_voiture, refresh1, "refresh1");
  GLADE_HOOKUP_OBJECT (liste_voiture, image7, "image7");
  GLADE_HOOKUP_OBJECT (liste_voiture, label8k, "label8k");
  GLADE_HOOKUP_OBJECT (liste_voiture, retourajouter, "retourajouter");
  GLADE_HOOKUP_OBJECT (liste_voiture, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (liste_voiture, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (liste_voiture, image3, "image3");
  GLADE_HOOKUP_OBJECT (liste_voiture, label9, "label9");
  GLADE_HOOKUP_OBJECT (liste_voiture, modifierunevoiture, "modifierunevoiture");
  GLADE_HOOKUP_OBJECT (liste_voiture, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (liste_voiture, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (liste_voiture, image13, "image13");
  GLADE_HOOKUP_OBJECT (liste_voiture, label24, "label24");
  GLADE_HOOKUP_OBJECT (liste_voiture, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (liste_voiture, treeviewvoiture, "treeviewvoiture");

  return liste_voiture;
}

GtkWidget*
create_modifier_voiture (void)
{
  GtkWidget *modifier_voiture;
  GtkWidget *fixed4;
  GtkWidget *image10;
  GtkWidget *cellview9;
  GdkColor cellview9_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *cellview10;
  GdkColor cellview10_bg_color = { 0, 64836, 64836, 64836 };
  GtkWidget *cellview11;
  GdkColor cellview11_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *cellview12;
  GdkColor cellview12_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *cellview13;
  GdkColor cellview13_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *cellview14;
  GdkColor cellview14_bg_color = { 0, 65535, 65535, 65535 };
  GtkWidget *label15k;
  GtkWidget *label16k;
  GtkWidget *label17k;
  GtkWidget *label18k;
  GtkWidget *label19k;
  GtkWidget *entrymarque_mod;
  GtkWidget *label20k;
  GtkWidget *entryserie_mod;
  GtkWidget *entryage_mod;
  GtkWidget *entrykilometrage_mod;
  GtkWidget *entryprix_mod;
  GtkWidget *entrydate_mod;
  GtkWidget *label21k;
  GtkWidget *validerchangement;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image11;
  GtkWidget *label22;
  GtkWidget *retourliste;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image12;
  GtkWidget *label23;

  modifier_voiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_voiture), _("Modifier une voiture"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (modifier_voiture), fixed4);

  image10 = create_pixmap (modifier_voiture, "ob_888a26_rent-a-car-tunisia.jpg");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed4), image10, 0, 0);
  gtk_widget_set_size_request (image10, 552, 424);

  cellview9 = gtk_cell_view_new ();
  gtk_widget_show (cellview9);
  gtk_fixed_put (GTK_FIXED (fixed4), cellview9, 32, 64);
  gtk_widget_set_size_request (cellview9, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview9), &cellview9_bg_color);

  cellview10 = gtk_cell_view_new ();
  gtk_widget_show (cellview10);
  gtk_fixed_put (GTK_FIXED (fixed4), cellview10, 32, 112);
  gtk_widget_set_size_request (cellview10, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview10), &cellview10_bg_color);

  cellview11 = gtk_cell_view_new ();
  gtk_widget_show (cellview11);
  gtk_fixed_put (GTK_FIXED (fixed4), cellview11, 32, 160);
  gtk_widget_set_size_request (cellview11, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview11), &cellview11_bg_color);

  cellview12 = gtk_cell_view_new ();
  gtk_widget_show (cellview12);
  gtk_fixed_put (GTK_FIXED (fixed4), cellview12, 32, 208);
  gtk_widget_set_size_request (cellview12, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview12), &cellview12_bg_color);

  cellview13 = gtk_cell_view_new ();
  gtk_widget_show (cellview13);
  gtk_fixed_put (GTK_FIXED (fixed4), cellview13, 32, 256);
  gtk_widget_set_size_request (cellview13, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview13), &cellview13_bg_color);

  cellview14 = gtk_cell_view_new ();
  gtk_widget_show (cellview14);
  gtk_fixed_put (GTK_FIXED (fixed4), cellview14, 32, 304);
  gtk_widget_set_size_request (cellview14, 112, 39);
  gtk_cell_view_set_background_color (GTK_CELL_VIEW (cellview14), &cellview14_bg_color);

  label15k = gtk_label_new (_("Marque :"));
  gtk_widget_show (label15k);
  gtk_fixed_put (GTK_FIXED (fixed4), label15k, 24, 64);
  gtk_widget_set_size_request (label15k, 128, 40);

  label16k = gtk_label_new (_("num de s\303\251rie :"));
  gtk_widget_show (label16k);
  gtk_fixed_put (GTK_FIXED (fixed4), label16k, 40, 112);
  gtk_widget_set_size_request (label16k, 96, 40);

  label17k = gtk_label_new (_("Age :"));
  gtk_widget_show (label17k);
  gtk_fixed_put (GTK_FIXED (fixed4), label17k, 64, 168);
  gtk_widget_set_size_request (label17k, 48, 24);

  label18k = gtk_label_new (_("Kilom\303\251trage :"));
  gtk_widget_show (label18k);
  gtk_fixed_put (GTK_FIXED (fixed4), label18k, 40, 208);
  gtk_widget_set_size_request (label18k, 96, 40);

  label19k = gtk_label_new (_("prix par jour :"));
  gtk_widget_show (label19k);
  gtk_fixed_put (GTK_FIXED (fixed4), label19k, 24, 256);
  gtk_widget_set_size_request (label19k, 120, 40);

  entrymarque_mod = gtk_entry_new ();
  gtk_widget_show (entrymarque_mod);
  gtk_fixed_put (GTK_FIXED (fixed4), entrymarque_mod, 176, 64);
  gtk_widget_set_size_request (entrymarque_mod, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymarque_mod), 8226);

  label20k = gtk_label_new (_("Date :"));
  gtk_widget_show (label20k);
  gtk_fixed_put (GTK_FIXED (fixed4), label20k, 48, 312);
  gtk_widget_set_size_request (label20k, 72, 32);

  entryserie_mod = gtk_entry_new ();
  gtk_widget_show (entryserie_mod);
  gtk_fixed_put (GTK_FIXED (fixed4), entryserie_mod, 176, 112);
  gtk_widget_set_size_request (entryserie_mod, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryserie_mod), 8226);

  entryage_mod = gtk_entry_new ();
  gtk_widget_show (entryage_mod);
  gtk_fixed_put (GTK_FIXED (fixed4), entryage_mod, 176, 168);
  gtk_widget_set_size_request (entryage_mod, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryage_mod), 8226);

  entrykilometrage_mod = gtk_entry_new ();
  gtk_widget_show (entrykilometrage_mod);
  gtk_fixed_put (GTK_FIXED (fixed4), entrykilometrage_mod, 176, 216);
  gtk_widget_set_size_request (entrykilometrage_mod, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrykilometrage_mod), 8226);

  entryprix_mod = gtk_entry_new ();
  gtk_widget_show (entryprix_mod);
  gtk_fixed_put (GTK_FIXED (fixed4), entryprix_mod, 176, 264);
  gtk_widget_set_size_request (entryprix_mod, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprix_mod), 8226);

  entrydate_mod = gtk_entry_new ();
  gtk_widget_show (entrydate_mod);
  gtk_fixed_put (GTK_FIXED (fixed4), entrydate_mod, 176, 312);
  gtk_widget_set_size_request (entrydate_mod, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydate_mod), 8226);

  label21k = gtk_label_new ("");
  gtk_widget_show (label21k);
  gtk_fixed_put (GTK_FIXED (fixed4), label21k, 176, 352);
  gtk_widget_set_size_request (label21k, 176, 72);

  validerchangement = gtk_button_new ();
  gtk_widget_show (validerchangement);
  gtk_fixed_put (GTK_FIXED (fixed4), validerchangement, 48, 360);
  gtk_widget_set_size_request (validerchangement, 136, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (validerchangement), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox6), image11, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox6), label22, FALSE, FALSE, 0);

  retourliste = gtk_button_new ();
  gtk_widget_show (retourliste);
  gtk_fixed_put (GTK_FIXED (fixed4), retourliste, 344, 360);
  gtk_widget_set_size_request (retourliste, 136, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (retourliste), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox7), image12, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox7), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) validerchangement, "clicked",
                    G_CALLBACK (on_validerchangement_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourliste, "clicked",
                    G_CALLBACK (on_retourliste_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_voiture, modifier_voiture, "modifier_voiture");
  GLADE_HOOKUP_OBJECT (modifier_voiture, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (modifier_voiture, image10, "image10");
  GLADE_HOOKUP_OBJECT (modifier_voiture, cellview9, "cellview9");
  GLADE_HOOKUP_OBJECT (modifier_voiture, cellview10, "cellview10");
  GLADE_HOOKUP_OBJECT (modifier_voiture, cellview11, "cellview11");
  GLADE_HOOKUP_OBJECT (modifier_voiture, cellview12, "cellview12");
  GLADE_HOOKUP_OBJECT (modifier_voiture, cellview13, "cellview13");
  GLADE_HOOKUP_OBJECT (modifier_voiture, cellview14, "cellview14");
  GLADE_HOOKUP_OBJECT (modifier_voiture, label15k, "label15k");
  GLADE_HOOKUP_OBJECT (modifier_voiture, label16k, "label16k");
  GLADE_HOOKUP_OBJECT (modifier_voiture, label17k, "label17k");
  GLADE_HOOKUP_OBJECT (modifier_voiture, label18k, "label18k");
  GLADE_HOOKUP_OBJECT (modifier_voiture, label19k, "label19k");
  GLADE_HOOKUP_OBJECT (modifier_voiture, entrymarque_mod, "entrymarque_mod");
  GLADE_HOOKUP_OBJECT (modifier_voiture, label20k, "label20k");
  GLADE_HOOKUP_OBJECT (modifier_voiture, entryserie_mod, "entryserie_mod");
  GLADE_HOOKUP_OBJECT (modifier_voiture, entryage_mod, "entryage_mod");
  GLADE_HOOKUP_OBJECT (modifier_voiture, entrykilometrage_mod, "entrykilometrage_mod");
  GLADE_HOOKUP_OBJECT (modifier_voiture, entryprix_mod, "entryprix_mod");
  GLADE_HOOKUP_OBJECT (modifier_voiture, entrydate_mod, "entrydate_mod");
  GLADE_HOOKUP_OBJECT (modifier_voiture, label21k, "label21k");
  GLADE_HOOKUP_OBJECT (modifier_voiture, validerchangement, "validerchangement");
  GLADE_HOOKUP_OBJECT (modifier_voiture, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modifier_voiture, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modifier_voiture, image11, "image11");
  GLADE_HOOKUP_OBJECT (modifier_voiture, label22, "label22");
  GLADE_HOOKUP_OBJECT (modifier_voiture, retourliste, "retourliste");
  GLADE_HOOKUP_OBJECT (modifier_voiture, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifier_voiture, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifier_voiture, image12, "image12");
  GLADE_HOOKUP_OBJECT (modifier_voiture, label23, "label23");

  return modifier_voiture;
}

