/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_voiture (void);
GtkWidget* create_ajouter_une_voiture (void);
GtkWidget* create_liste_voiture (void);
GtkWidget* create_modifier_voiture (void);
