/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Reclamation_client (void)
{
  GtkWidget *Reclamation_client;
  GtkWidget *fixedanis1;
  GtkWidget *image11;
  GtkWidget *labelanis1;
  GtkWidget *creation__;
  GtkWidget *buttonanis2;
  GtkWidget *buttonanis3;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3;

  Reclamation_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Reclamation_client), _("Reclamation_client"));

  fixedanis1 = gtk_fixed_new ();
  gtk_widget_show (fixedanis1);
  gtk_container_add (GTK_CONTAINER (Reclamation_client), fixedanis1);

  image11 = create_pixmap (Reclamation_client, "76775178_811276792662475_3862460601779355648_n (1).png");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixedanis1), image11, 0, 0);
  gtk_widget_set_size_request (image11, 800, 469);

  labelanis1 = gtk_label_new (_("Reclamation client "));
  gtk_widget_show (labelanis1);
  gtk_fixed_put (GTK_FIXED (fixedanis1), labelanis1, 296, 40);
  gtk_widget_set_size_request (labelanis1, 200, 20);

  creation__ = gtk_button_new_with_mnemonic (_("creation     "));
  gtk_widget_show (creation__);
  gtk_fixed_put (GTK_FIXED (fixedanis1), creation__, 192, 232);
  gtk_widget_set_size_request (creation__, 68, 40);

  buttonanis2 = gtk_button_new_with_mnemonic (_("Consulter mes reclamations"));
  gtk_widget_show (buttonanis2);
  gtk_fixed_put (GTK_FIXED (fixedanis1), buttonanis2, 328, 232);
  gtk_widget_set_size_request (buttonanis2, 210, 40);

  buttonanis3 = gtk_button_new ();
  gtk_widget_show (buttonanis3);
  gtk_fixed_put (GTK_FIXED (fixedanis1), buttonanis3, 56, 416);
  gtk_widget_set_size_request (buttonanis3, 96, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonanis3), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) creation__, "clicked",
                    G_CALLBACK (on_creation___clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonanis2, "clicked",
                    G_CALLBACK (on_buttonanis2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonanis3, "clicked",
                    G_CALLBACK (on_buttonanis3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reclamation_client, Reclamation_client, "Reclamation_client");
  GLADE_HOOKUP_OBJECT (Reclamation_client, fixedanis1, "fixedanis1");
  GLADE_HOOKUP_OBJECT (Reclamation_client, image11, "image11");
  GLADE_HOOKUP_OBJECT (Reclamation_client, labelanis1, "labelanis1");
  GLADE_HOOKUP_OBJECT (Reclamation_client, creation__, "creation__");
  GLADE_HOOKUP_OBJECT (Reclamation_client, buttonanis2, "buttonanis2");
  GLADE_HOOKUP_OBJECT (Reclamation_client, buttonanis3, "buttonanis3");
  GLADE_HOOKUP_OBJECT (Reclamation_client, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Reclamation_client, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Reclamation_client, image1, "image1");
  GLADE_HOOKUP_OBJECT (Reclamation_client, label3, "label3");

  return Reclamation_client;
}

GtkWidget*
create_Creer (void)
{
  GtkWidget *Creer;
  GtkWidget *fixedanis2;
  GtkWidget *entryanis1;
  GtkWidget *entryanis2;
  GtkWidget *entryanis3;
  GtkWidget *labelanis20;
  GtkWidget *comboboxanis1;
  GtkWidget *labelanis4;
  GtkWidget *labelanis18;
  GtkWidget *labelanis24;
  GtkWidget *labelanis25;
  GtkWidget *labelanis26;
  GtkWidget *labelanis6;
  GtkWidget *labelanis5;
  GtkWidget *labelanis8;
  GtkWidget *labelanis15;
  GtkWidget *buttonanis4;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label7;
  GtkWidget *buttonanis5;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label9;
  GtkWidget *buttonanis8;

  Creer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Creer), _("Creer"));

  fixedanis2 = gtk_fixed_new ();
  gtk_widget_show (fixedanis2);
  gtk_container_add (GTK_CONTAINER (Creer), fixedanis2);

  entryanis1 = gtk_entry_new ();
  gtk_widget_show (entryanis1);
  gtk_fixed_put (GTK_FIXED (fixedanis2), entryanis1, 144, 136);
  gtk_widget_set_size_request (entryanis1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryanis1), 8226);

  entryanis2 = gtk_entry_new ();
  gtk_widget_show (entryanis2);
  gtk_fixed_put (GTK_FIXED (fixedanis2), entryanis2, 40, 208);
  gtk_widget_set_size_request (entryanis2, 232, 59);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryanis2), 8226);

  entryanis3 = gtk_entry_new ();
  gtk_widget_show (entryanis3);
  gtk_fixed_put (GTK_FIXED (fixedanis2), entryanis3, 112, 48);
  gtk_widget_set_size_request (entryanis3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryanis3), 8226);

  labelanis20 = gtk_label_new ("");
  gtk_widget_show (labelanis20);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis20, 88, 280);
  gtk_widget_set_size_request (labelanis20, 176, 17);

  comboboxanis1 = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxanis1);
  gtk_fixed_put (GTK_FIXED (fixedanis2), comboboxanis1, 144, 88);
  gtk_widget_set_size_request (comboboxanis1, 145, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxanis1), _("Service_interne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxanis1), _("prestation"));

  labelanis4 = gtk_label_new (_("Creer reclamation"));
  gtk_widget_show (labelanis4);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis4, 88, 8);
  gtk_widget_set_size_request (labelanis4, 150, 20);

  labelanis18 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (labelanis18);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis18, 0, 48);
  gtk_widget_set_size_request (labelanis18, 112, 16);

  labelanis24 = gtk_label_new ("");
  gtk_widget_show (labelanis24);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis24, 288, 48);
  gtk_widget_set_size_request (labelanis24, 216, 25);

  labelanis25 = gtk_label_new ("");
  gtk_widget_show (labelanis25);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis25, 312, 136);
  gtk_widget_set_size_request (labelanis25, 208, 40);

  labelanis26 = gtk_label_new ("");
  gtk_widget_show (labelanis26);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis26, 288, 200);
  gtk_widget_set_size_request (labelanis26, 208, 88);

  labelanis6 = gtk_label_new (_("Ecrire votre reclamation "));
  gtk_widget_show (labelanis6);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis6, 8, 176);
  gtk_widget_set_size_request (labelanis6, 200, 20);

  labelanis5 = gtk_label_new (_("Date de service:"));
  gtk_widget_show (labelanis5);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis5, 0, 144);
  gtk_widget_set_size_request (labelanis5, 150, 20);

  labelanis8 = gtk_label_new (_("Type de service:"));
  gtk_widget_show (labelanis8);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis8, 0, 88);
  gtk_widget_set_size_request (labelanis8, 150, 20);

  labelanis15 = gtk_label_new ("");
  gtk_widget_show (labelanis15);
  gtk_fixed_put (GTK_FIXED (fixedanis2), labelanis15, 48, 272);
  gtk_widget_set_size_request (labelanis15, 250, 20);

  buttonanis4 = gtk_button_new ();
  gtk_widget_show (buttonanis4);
  gtk_fixed_put (GTK_FIXED (fixedanis2), buttonanis4, 32, 304);
  gtk_widget_set_size_request (buttonanis4, 100, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonanis4), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  buttonanis5 = gtk_button_new ();
  gtk_widget_show (buttonanis5);
  gtk_fixed_put (GTK_FIXED (fixedanis2), buttonanis5, 152, 304);
  gtk_widget_set_size_request (buttonanis5, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonanis5), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox3), label9, FALSE, FALSE, 0);

  buttonanis8 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonanis8);
  gtk_fixed_put (GTK_FIXED (fixedanis2), buttonanis8, 248, 304);
  gtk_widget_set_size_request (buttonanis8, 96, 32);

  g_signal_connect ((gpointer) buttonanis4, "clicked",
                    G_CALLBACK (on_buttonanis4_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonanis5, "clicked",
                    G_CALLBACK (on_buttonanis5_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonanis8, "clicked",
                    G_CALLBACK (on_buttonanis8_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Creer, Creer, "Creer");
  GLADE_HOOKUP_OBJECT (Creer, fixedanis2, "fixedanis2");
  GLADE_HOOKUP_OBJECT (Creer, entryanis1, "entryanis1");
  GLADE_HOOKUP_OBJECT (Creer, entryanis2, "entryanis2");
  GLADE_HOOKUP_OBJECT (Creer, entryanis3, "entryanis3");
  GLADE_HOOKUP_OBJECT (Creer, labelanis20, "labelanis20");
  GLADE_HOOKUP_OBJECT (Creer, comboboxanis1, "comboboxanis1");
  GLADE_HOOKUP_OBJECT (Creer, labelanis4, "labelanis4");
  GLADE_HOOKUP_OBJECT (Creer, labelanis18, "labelanis18");
  GLADE_HOOKUP_OBJECT (Creer, labelanis24, "labelanis24");
  GLADE_HOOKUP_OBJECT (Creer, labelanis25, "labelanis25");
  GLADE_HOOKUP_OBJECT (Creer, labelanis26, "labelanis26");
  GLADE_HOOKUP_OBJECT (Creer, labelanis6, "labelanis6");
  GLADE_HOOKUP_OBJECT (Creer, labelanis5, "labelanis5");
  GLADE_HOOKUP_OBJECT (Creer, labelanis8, "labelanis8");
  GLADE_HOOKUP_OBJECT (Creer, labelanis15, "labelanis15");
  GLADE_HOOKUP_OBJECT (Creer, buttonanis4, "buttonanis4");
  GLADE_HOOKUP_OBJECT (Creer, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Creer, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Creer, image2, "image2");
  GLADE_HOOKUP_OBJECT (Creer, label7, "label7");
  GLADE_HOOKUP_OBJECT (Creer, buttonanis5, "buttonanis5");
  GLADE_HOOKUP_OBJECT (Creer, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Creer, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Creer, image3, "image3");
  GLADE_HOOKUP_OBJECT (Creer, label9, "label9");
  GLADE_HOOKUP_OBJECT (Creer, buttonanis8, "buttonanis8");

  return Creer;
}

GtkWidget*
create_consulter (void)
{
  GtkWidget *consulter;
  GtkWidget *fixed4;
  GtkWidget *treeviewanis1;
  GtkWidget *labelanis14;
  GtkWidget *buttonanis7;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label12;

  consulter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (consulter), _("consulter"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (consulter), fixed4);

  treeviewanis1 = gtk_tree_view_new ();
  gtk_widget_show (treeviewanis1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeviewanis1, 8, 64);
  gtk_widget_set_size_request (treeviewanis1, 904, 216);

  labelanis14 = gtk_label_new (_("Consulter mes reclamations"));
  gtk_widget_show (labelanis14);
  gtk_fixed_put (GTK_FIXED (fixed4), labelanis14, 104, 16);
  gtk_widget_set_size_request (labelanis14, 250, 25);

  buttonanis7 = gtk_button_new ();
  gtk_widget_show (buttonanis7);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonanis7, 56, 296);
  gtk_widget_set_size_request (buttonanis7, 96, 37);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonanis7), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox5), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonanis7, "clicked",
                    G_CALLBACK (on_buttonanis7_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (consulter, consulter, "consulter");
  GLADE_HOOKUP_OBJECT (consulter, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (consulter, treeviewanis1, "treeviewanis1");
  GLADE_HOOKUP_OBJECT (consulter, labelanis14, "labelanis14");
  GLADE_HOOKUP_OBJECT (consulter, buttonanis7, "buttonanis7");
  GLADE_HOOKUP_OBJECT (consulter, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (consulter, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (consulter, image5, "image5");
  GLADE_HOOKUP_OBJECT (consulter, label12, "label12");

  return consulter;
}

GtkWidget*
create_principal (void)
{
  GtkWidget *principal;
  GtkWidget *fixedanis6;

  principal = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (principal), _("principal"));

  fixedanis6 = gtk_fixed_new ();
  gtk_widget_show (fixedanis6);
  gtk_container_add (GTK_CONTAINER (principal), fixedanis6);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (principal, principal, "principal");
  GLADE_HOOKUP_OBJECT (principal, fixedanis6, "fixedanis6");

  return principal;
}

GtkWidget*
create_employe (void)
{
  GtkWidget *employe;
  GtkWidget *fixedanis7;
  GtkWidget *treeviewanis2;
  GtkWidget *entryanis4;
  GtkWidget *entryanis5;
  GtkWidget *labelanis22;
  GtkWidget *labelanis20;
  GtkWidget *labelanis27;
  GtkWidget *labelanis16;
  GtkWidget *labelanis23;
  GtkWidget *buttonanis14;
  GtkWidget *image10;
  GtkWidget *buttonanis9;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label13;
  GtkWidget *buttonanis13;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label19;
  GtkWidget *buttonanis10;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label17;
  GtkWidget *buttonanis12;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label21;

  employe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (employe), _("window1"));

  fixedanis7 = gtk_fixed_new ();
  gtk_widget_show (fixedanis7);
  gtk_container_add (GTK_CONTAINER (employe), fixedanis7);

  treeviewanis2 = gtk_tree_view_new ();
  gtk_widget_show (treeviewanis2);
  gtk_fixed_put (GTK_FIXED (fixedanis7), treeviewanis2, 16, 56);
  gtk_widget_set_size_request (treeviewanis2, 392, 184);

  entryanis4 = gtk_entry_new ();
  gtk_widget_show (entryanis4);
  gtk_fixed_put (GTK_FIXED (fixedanis7), entryanis4, 496, 120);
  gtk_widget_set_size_request (entryanis4, 360, 99);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryanis4), 8226);

  entryanis5 = gtk_entry_new ();
  gtk_widget_show (entryanis5);
  gtk_fixed_put (GTK_FIXED (fixedanis7), entryanis5, 552, 56);
  gtk_widget_set_size_request (entryanis5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryanis5), 8226);

  labelanis22 = gtk_label_new ("");
  gtk_widget_show (labelanis22);
  gtk_fixed_put (GTK_FIXED (fixedanis7), labelanis22, 520, 216);
  gtk_widget_set_size_request (labelanis22, 312, 33);

  labelanis20 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (labelanis20);
  gtk_fixed_put (GTK_FIXED (fixedanis7), labelanis20, 448, 64);
  gtk_widget_set_size_request (labelanis20, 112, 16);

  labelanis27 = gtk_label_new (_(" "));
  gtk_widget_show (labelanis27);
  gtk_fixed_put (GTK_FIXED (fixedanis7), labelanis27, 504, 232);
  gtk_widget_set_size_request (labelanis27, 352, 89);

  labelanis16 = gtk_label_new (_("Affichage des reclamations"));
  gtk_widget_show (labelanis16);
  gtk_fixed_put (GTK_FIXED (fixedanis7), labelanis16, 96, 8);
  gtk_widget_set_size_request (labelanis16, 210, 20);

  labelanis23 = gtk_label_new ("");
  gtk_widget_show (labelanis23);
  gtk_fixed_put (GTK_FIXED (fixedanis7), labelanis23, 552, 96);
  gtk_widget_set_size_request (labelanis23, 232, 17);

  buttonanis14 = gtk_button_new ();
  gtk_widget_show (buttonanis14);
  gtk_fixed_put (GTK_FIXED (fixedanis7), buttonanis14, 408, 56);
  gtk_widget_set_size_request (buttonanis14, 48, 29);

  image10 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (buttonanis14), image10);

  buttonanis9 = gtk_button_new ();
  gtk_widget_show (buttonanis9);
  gtk_fixed_put (GTK_FIXED (fixedanis7), buttonanis9, 752, 56);
  gtk_widget_set_size_request (buttonanis9, 112, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonanis9), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox6), label13, FALSE, FALSE, 0);

  buttonanis13 = gtk_button_new ();
  gtk_widget_show (buttonanis13);
  gtk_fixed_put (GTK_FIXED (fixedanis7), buttonanis13, 872, 56);
  gtk_widget_set_size_request (buttonanis13, 112, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonanis13), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox8), label19, FALSE, FALSE, 0);

  buttonanis10 = gtk_button_new ();
  gtk_widget_show (buttonanis10);
  gtk_fixed_put (GTK_FIXED (fixedanis7), buttonanis10, 32, 256);
  gtk_widget_set_size_request (buttonanis10, 100, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonanis10), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);

  buttonanis12 = gtk_button_new ();
  gtk_widget_show (buttonanis12);
  gtk_fixed_put (GTK_FIXED (fixedanis7), buttonanis12, 872, 128);
  gtk_widget_set_size_request (buttonanis12, 112, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonanis12), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Reponse  "));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox9), label21, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonanis14, "clicked",
                    G_CALLBACK (on_buttonanis14_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonanis9, "clicked",
                    G_CALLBACK (on_buttonanis9_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonanis13, "clicked",
                    G_CALLBACK (on_buttonanis13_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonanis10, "clicked",
                    G_CALLBACK (on_buttonanis10_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonanis12, "clicked",
                    G_CALLBACK (on_buttonanis12_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (employe, employe, "employe");
  GLADE_HOOKUP_OBJECT (employe, fixedanis7, "fixedanis7");
  GLADE_HOOKUP_OBJECT (employe, treeviewanis2, "treeviewanis2");
  GLADE_HOOKUP_OBJECT (employe, entryanis4, "entryanis4");
  GLADE_HOOKUP_OBJECT (employe, entryanis5, "entryanis5");
  GLADE_HOOKUP_OBJECT (employe, labelanis22, "labelanis22");
  GLADE_HOOKUP_OBJECT (employe, labelanis20, "labelanis20");
  GLADE_HOOKUP_OBJECT (employe, labelanis27, "labelanis27");
  GLADE_HOOKUP_OBJECT (employe, labelanis16, "labelanis16");
  GLADE_HOOKUP_OBJECT (employe, labelanis23, "labelanis23");
  GLADE_HOOKUP_OBJECT (employe, buttonanis14, "buttonanis14");
  GLADE_HOOKUP_OBJECT (employe, image10, "image10");
  GLADE_HOOKUP_OBJECT (employe, buttonanis9, "buttonanis9");
  GLADE_HOOKUP_OBJECT (employe, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (employe, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (employe, image6, "image6");
  GLADE_HOOKUP_OBJECT (employe, label13, "label13");
  GLADE_HOOKUP_OBJECT (employe, buttonanis13, "buttonanis13");
  GLADE_HOOKUP_OBJECT (employe, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (employe, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (employe, image8, "image8");
  GLADE_HOOKUP_OBJECT (employe, label19, "label19");
  GLADE_HOOKUP_OBJECT (employe, buttonanis10, "buttonanis10");
  GLADE_HOOKUP_OBJECT (employe, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (employe, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (employe, image7, "image7");
  GLADE_HOOKUP_OBJECT (employe, label17, "label17");
  GLADE_HOOKUP_OBJECT (employe, buttonanis12, "buttonanis12");
  GLADE_HOOKUP_OBJECT (employe, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (employe, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (employe, image9, "image9");
  GLADE_HOOKUP_OBJECT (employe, label21, "label21");

  return employe;
}

GtkWidget*
create_principal1 (void)
{
  GtkWidget *principal1;
  GtkWidget *fixedanis8;
  GtkWidget *buttonanis11;

  principal1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (principal1), _("window2"));

  fixedanis8 = gtk_fixed_new ();
  gtk_widget_show (fixedanis8);
  gtk_container_add (GTK_CONTAINER (principal1), fixedanis8);

  buttonanis11 = gtk_button_new_with_mnemonic (_("  Affichage    "));
  gtk_widget_show (buttonanis11);
  gtk_fixed_put (GTK_FIXED (fixedanis8), buttonanis11, 104, 56);
  gtk_widget_set_size_request (buttonanis11, 184, 48);

  g_signal_connect ((gpointer) buttonanis11, "clicked",
                    G_CALLBACK (on_buttonanis11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (principal1, principal1, "principal1");
  GLADE_HOOKUP_OBJECT (principal1, fixedanis8, "fixedanis8");
  GLADE_HOOKUP_OBJECT (principal1, buttonanis11, "buttonanis11");

  return principal1;
}

