/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_reservations (void);
GtkWidget* create_affichage (void);
GtkWidget* create_vol (void);
GtkWidget* create_modificationvol (void);
GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window6 (void);
GtkWidget* create_skytravel (void);
GtkWidget* create_connexion (void);
GtkWidget* create_menuadmin (void);
GtkWidget* create_menuagent (void);
GtkWidget* create_menuclient (void);
GtkWidget* create_clientadmin (void);
GtkWidget* create_window3zahra (void);
GtkWidget* create_window5zahra (void);
GtkWidget* create_cataloguehotel (void);
GtkWidget* create_gestion_voiture (void);
GtkWidget* create_ajouter_une_voiture (void);
GtkWidget* create_liste_voiture (void);
GtkWidget* create_modifier_voiture (void);
GtkWidget* create_liste_voitureclient (void);
GtkWidget* create_Reclamation_client (void);
GtkWidget* create_Creer (void);
GtkWidget* create_consulter (void);
GtkWidget* create_principal (void);
GtkWidget* create_employe (void);
GtkWidget* create_AGwindowAffichage (void);
GtkWidget* create_AGwindowAjout (void);
GtkWidget* create_AGwindowModifier (void);
GtkWidget* create_AGwindowCatalogue (void);
GtkWidget* create_AGwindowConfirmation (void);
GtkWidget* create_reservationagent (void);
GtkWidget* create_gestionfacture (void);
